packages/extension-koni-base/src/api/endpoints.ts

#125 - Update Polkadex ParaID
Dagmara H - Polkadex
As a heads up we'll be entering the Crowdloan on Monday, April 4th (that is one day earlier than previously planned). We’ll share with you our paraID as soon as we have it. It would be great if you could follow up with the adjustments on your side as soon as possible 🙏 We also made some changes to the crowdloan structure and rewards distribution, making it more attractive for the contributors 🙂
Crowdloan Structure:
DOT Cap: 1M
PDEX Pool: 2M
Base Reward (PDEX/DOT): 2+
Lease Period: 8-15
Ending Block: 10,881,400
Para ID: 2040

#125 - Update Polkadex ParaID

---

packages/extension-koni-ui/src/Popup/Accounts/Account.tsx

Disable button Change Avatar in popup screen (only applies to Firefox browser)

Avatar All Account does not update when changing from collapse (popup) in Firefox browser

---

patches/react-tooltip+4.2.21.patch

Pull request for task #224
Fix bug tooltip not showing on the popup view on firefox browser

Fix bug tooltip not showing on the popup view on firefox browser

---

packages/extension-koni-base/src/background/handlers/State.ts

Related issue:
#392 
Cause:
Wrong coingeckoKey in store leads to incorrect price
Default coingeckoKey doesn't override custom key
Solution:
Prioritize default coingeckoKey, custom key isn't used much by users anyway

Fix bug not showing GLMR price

---

packages/extension-koni-ui/src/util/chainBalancesApi.tsx

- #206 
- Fix Total Balance was wrong due to DOT Crowd loan for Acala
- Parallel Token Price was wrong
- Ignore LCDOT token price
- Don't update coinGeckoKey for token if parachain not launch
- No
- No

[Issue-206] Total Balance was wrong due to DOT Crowd loan for Acala & Parallel Token Price was wrong

---

packages/extension-koni-ui/src/Popup/Accounts/AddAccount.tsx

- #254 
- Add feature to allow first-time users to import their Metamask private keys
- Add button `Import private key from Metamask` in `AddAccount` screen
- No
- No

[Issue-254] Add feature to allow first-time users to import their Metamask private keys

---

packages/extension-koni-ui/src/util/index.ts

- #584
- Fix cannot open history in moonbase
- Fix `undefined` url subscan 
- No
- No

[Issue-584] Can't view Transaction history of Moonbase Alpha network

---

packages/extension-koni-ui/src/Popup/Sending/SendFund.tsx

[Issue 861] Hot fix update warning when account cannot be reaped

---

packages/extension-koni-ui/src/Popup/Keyring/ApplyMasterPassword/index.tsx
packages/extension-koni-ui/src/Popup/Settings/Security/ManageWebsiteAccess/Detail.tsx

- #1139
- Update counter
- Update counter
- No
- No

[Issue-1139] UpgradeUI - Show counter of accounts to which the master password needs to be applied is incorrect

---

packages/extension-koni-ui/src/Popup/Settings/Security/ManageWebsiteAccess/Detail.tsx

- #1234
- Display id if site empty
- Display id if site empty
- No
- No

[Issue-1234] Show the alternate title name of Dapp in the Manage website access screen

---

packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/index.tsx

- #1394
- Rearrange the position of `All accounts`
- Rearrange the position of `All accounts`
- No
- No

[Issue-1394] Fix the "All accounts" on top in the List account (Firefox browser)

---

packages/extension-koni-ui/src/Popup/Root.tsx

- #1401
- Allow `securityUrl` when no accounts
- Allow `securityUrl` when no accounts
- No
- No

[issue-1401] Handle case access camera setting whe have no account on the wallet

---

packages/extension-base/src/defaults.ts
packages/extension-base/src/koni/background/handlers/State.ts
packages/extension-koni-ui/src/Popup/Account/ImportSeedPhrase.tsx
packages/extension-koni-ui/src/Popup/Account/NewSeedPhrase.tsx
packages/extension-koni-ui/src/Popup/Confirmations/variants/AuthorizeConfirmation.tsx
packages/extension-koni-ui/src/Popup/CreateDone.tsx
packages/extension-koni-ui/src/Popup/Root.tsx
packages/extension-koni-ui/src/Popup/Welcome.tsx
packages/extension-koni-ui/src/components/BackgroundExpandView.tsx
packages/extension-koni-ui/src/components/Modal/Account/NewAccountModal.tsx
packages/extension-koni-ui/src/components/PinExtensionMessage.tsx
packages/extension-koni-ui/src/components/SocialButtonGroup.tsx
packages/extension-koni-ui/src/components/WordPhrase.tsx
packages/extension-koni-ui/src/components/index.ts
packages/extension-koni-ui/src/constants/account.ts
packages/extension-koni-ui/src/themes.ts
packages/extension-koni-ui/src/utils/common/browser.ts

- #1560
- #1229 
- Add download file action on `Create new seed phrase` screen
- Open expand view after install
- Update UI for expand view
- Add download file action on `Create new seed phrase` screen
- Open expand view after install
- Update UI for expand view
- No
- No

[Issue-1560] Allow user download seed phrase file; [Issue-1229] Resolve problems with expand view

---

packages/extension-base/src/koni/background/handlers/Extension.ts

- #1657
- Fix don't validate receiver balance
- Fix don't validate receiver balance
- No
- No

[Issue-1657] Do not validate amount of the recipient address when send on-chain

---

packages/extension-koni-ui/src/components/Modal/ConfirmationModal.tsx
packages/extension-koni-ui/src/constants/modal.ts

- #1888
- Fix not show confirmation popup in case create transaction with popup
- Fix not show confirmation popup in case create transaction with popup
- No
- No

[Issue-1888] WebApp - Do not show confirmation after performing any transaction with extension account

---

packages/extension-koni-ui/src/components/Field/PoolSelector.tsx
packages/extension-koni-ui/src/components/SelectValidatorInput.tsx

- #2020
- Hide the AutoSelect validator/collator/dApp button if this method is not supported
- Hide the AutoSelect validator/collator/dApp button if this method is not supported
- No
- No

[Issue-2020] Hide the AutoSelect validator/collator/dApp button if this method is not supported

---

packages/extension-base/src/services/setting-service/SettingService.ts

- #2146
- Fix error when get setting
- Fix error when get setting
- No
- No

[Issue-2146] Re-check bug undefined is not an object when perform transaction

---

packages/extension-koni-ui/src/components/Modal/BaseModal.tsx
packages/extension-koni-ui/src/components/Modal/BaseSelectModal.tsx

Actual: Modal move to center then snap back to the right
Expect: Modal animation must show normally

[Issue 2211] Effect when open modal Select token, Select account in case Buy token 

---

packages/extension-koni-ui/src/Popup/Account/ImportSeedPhrase.tsx

Describe the bug
Version test: https://fcc535f4.subwallet-webapp.pages.dev/
To reproduce the bug
Steps:
Go to Import account -> Import from seed phrase
Click on Back button
Observe the displayed screen
Actual: Back to Select account type screen
Expect: Back to Import account screen

[Issue 1958] WebApp - Navigate incorrect in case back to Import account

---

packages/extension-base/src/constants/staking.ts

- #2385
- Add default pool for Aleph Zero
- Add default pool for Aleph Zero
- No
- No

[Issue-2385] Add Azero Domains Pool & Validator as default option when users stake A0

---

packages/extension-koni-ui/src/hooks/history/useHistorySelection.tsx

[Issue-2397] Show "select account" on the history screen in case disconnect injected account

---

packages/extension-koni-ui/src/Popup/Home/Tokens/DetailModal.tsx

[Issue-2429] Do not display the account in the account details tab in case the entire account balance is locked

---

packages/extension-koni-ui/src/components/History/HistoryItem.tsx

**Describe the bug**
Show $balance = NaN in the history screen when get price service is down
Expect: Show $balance = 0

[Issue 2393] WebApp - Show $balance = NaN in the history screen when get price service is down

---

packages/extension-koni-ui/src/Popup/Home/Tokens/DetailModal.tsx
packages/extension-koni-ui/src/components/TokenItem/AccountTokenBalanceItem.tsx

**Describe the bug**
Show incorrect account on the Token detail screen when disconnect account injected
**To Reproduce**
Steps to reproduce the behavior:
1. Open the WebApp
2. Perform connecting extension successfully
3. Switch to All accounts mode
4. Go to the token details screen of any token (Substrate token)
5. Observe the list token displayed
6. Disconnected any Substrate account on Extension
7. Back to token details screen on WebApp then observe the list token displayed again
**Actual:** Still shows account disconnected
- Only show address, not show account name
**Expect:** Do not show disconnected account

[Issue 2394] WebApp - Show incorrect account on the Token detail screen when disconnect account injected

---

packages/extension-base/src/services/balance-service/helpers/subscribe/balance.ts

[Issue-2616] Fix show incorrect token in case the wallet has only 1 account type

---

packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/index.tsx

Issue-2742] Extension - Still display start earning screen although back to earning positions/ Earning options screen

---

packages/extension-koni-ui/src/components/TokenItem/AccountTokenBalanceItem.tsx

- #3752
- Update logic show address on balance detail modal
- Update logic show address on balance detail modal
- No
- No

[Issue-3752] Extension - Update address for TON testnet in the token detail screen on All accounts mode

---

packages/extension-base/src/services/keyring-service/context/handlers/Modify.ts

- #3772
- Fix wrong current account after remove account
- Fix wrong current account after remove account
- No
- No

[Issue-3772] Still show All accounts in case wallet has only 1 account after removing account

---

packages/extension-base/src/koni/background/handlers/Extension.ts
packages/extension-koni-ui/src/Popup/Confirmations/variants/ConnectWalletConnectConfirmation.tsx
packages/extension-koni-ui/src/components/WalletConnect/Account/WCAccountSelect.tsx
packages/extension-koni-ui/src/components/WalletConnect/Network/WCNetworkSelected.tsx
packages/extension-koni-ui/src/hooks/wallet-connect/useSelectWalletConnectAccount.ts
packages/extension-koni-ui/src/types/walletConnect.ts
packages/extension-koni-ui/src/utils/walletConnect/index.ts

- #3870
- [WC] Allow substrate network use evm address to connect
- [WC] Allow substrate network use evm address to connect
- No
- No

[Issue-3870] WalletConnect - Allow Polkadot namespace use EVM address

---

packages/extension-base/src/services/earning-service/handlers/native-staking/relay-chain.ts

- #4522
- Cannot withdraw on Westend Asset Hub
- Cannot withdraw on Westend Asset Hub
- No
- No

[Issue-4522] Extension - Cannot withdraw on Westend Asset Hub
