- packages/extension-koni-ui/src/Popup/ImportQr.tsx
- packages/extension-koni-ui/src/Popup/RestoreJson.tsx
- #90 
Update Import Account screen layout 
- Bring Account List to Password Input bottom
- Hide Account List overflow 
- Make transparent Account List overflow
No
> [Account] [Import] [Batch] update UI

- packages/extension-koni-base/src/api/endpoints.ts
Fix Phala provider and SubSocialX chain name
> Fix Phala provider and SubSocialX chain name

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/dotsama/balance.ts
- packages/extension-koni-base/src/api/dotsama/registry.ts
- packages/extension-koni-base/src/api/web3/transfer.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
#32 Add support transfer token of Moonbeam base networks via ERC20 contract
> Add support transfer token of Moonbeam base networks via ERC20 contract

- packages/extension-koni-ui/src/Popup/AuthManagement/index.tsx
- packages/extension-koni-ui/src/Popup/ImportMetamaskPrivateKey/MetamaskPrivateKeyImport.tsx
- packages/extension-koni-ui/src/Popup/ImportSeed/SeedAndPath.tsx
- packages/extension-koni-ui/src/Popup/Settings/GeneralSetting.tsx
- packages/extension-koni-ui/src/Popup/Settings/index.tsx
Update UI Settings screen
- Remove unused Setting Item and add Allow Camera QR Access
> Update new Settings screen

- packages/extension-koni-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
- packages/extension-koni-ui/src/Popup/Authorize/ConnectAccount.tsx
- packages/extension-koni-ui/src/Popup/Authorize/Request.tsx
filter EVM acc for Substrate DApp
Add cursor = pointer in grant access screen
> Improve UI and filter evm account from authorize auth management

- packages/extension-koni-base/src/api/coingecko.ts
#92 Fix error can not see balance price of AstarEVM
> #92 Fix error can not see balance price of AstarEVM

- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-base/src/background/subscription.ts
- packages/extension-koni-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
- packages/extension-koni-ui/src/Popup/AuthManagement/WebsiteEntryAccount.tsx
- packages/extension-koni-ui/src/Popup/AuthManagement/index.tsx
- Fix bug not migrate site access
- Fix UI Auth Management screen
- Refactor code
> Fix bug not migrate site access, fix UI Auth Management screen, refactor code

- packages/extension-koni-base/build-cjs/api/coingecko.js
- packages/extension-koni-base/build-cjs/api/dotsama/api-helper/index.js
- packages/extension-koni-base/build-cjs/api/dotsama/balance.js
- packages/extension-koni-base/src/api/coingecko.ts
- packages/extension-koni-base/src/api/dotsama/api-helper/index.ts
- packages/extension-koni-base/src/api/dotsama/balance.ts
- packages/extension-koni-base/src/api/endpoints.ts
- packages/extension-koni-base/src/api/predefineChainTokens.ts
- packages/extension-koni-ui/src/assets/logo/index.ts
#136 
- Add Shiden - EVM into network list
- Add Support fetch Shidden - EVM balances and tokens
> #136 Add support Shiden - EVM balances and tokens

- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
Fix bug Quatity of the account incorrect when
-  add account
-  derive account
-  restore account
-  import account
-  forget account
> Fix bug Quatity of the account incorrect when add or remove account

- packages/extension-koni-base/src/background/handlers/State.ts
- #115 
- Fix bug forget account which import by json
- Catch exception refList undefined (which cause crash action)
- No
> [#115] Fix not automatically turn off Forget Account screen

- packages/extension-koni-ui/src/Popup/AuthManagement/index.tsx
- packages/extension-koni-ui/src/Popup/Settings/GeneralSetting.tsx
Fix default language value
Fix show hide Forget Confirm Modal condition
> Fix UI in General Settings, Auth Management

- packages/extension-koni-ui/src/Popup/Accounts/AddAccount.tsx
- packages/extension-koni/public/locales/en/translation.json
- packages/extension-koni/public/locales/fr/translation.json
- packages/extension-koni/public/locales/pl/translation.json
- packages/extension-koni/public/locales/th/translation.json
- packages/extension-koni/public/locales/tr/translation.json
- packages/extension-koni/public/locales/ur/translation.json
- packages/extension-koni/public/locales/vi/translation.json
- packages/extension-koni/public/locales/zh/translation.json
- packages/extension-ui/src/partials/MenuAdd.tsx
- packages/extension/public/locales/en/translation.json
- packages/extension/public/locales/fr/translation.json
- packages/extension/public/locales/pl/translation.json
- packages/extension/public/locales/th/translation.json
- packages/extension/public/locales/tr/translation.json
- packages/extension/public/locales/ur/translation.json
- packages/extension/public/locales/zh/translation.json
- #156 
- Change Text
- Change "Restore account from backup JSON file" to "Restore account from JSON backup file"
- No
- No
> [Issue-156] Grammar error on button

- packages/extension-koni-ui/src/partials/AccountMenuSettings.tsx
Fix grammar error on button Import Seed
>  Change "Seed Phase" to "Seed Phrase"

- packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
Support Astarnaut and AstarCats NFT on Astar
> Support Astarnaut and AstarCats NFT on Astar

- packages/extension-koni-base/src/api/nft/config.ts
- packages/extension-koni-base/src/api/nft/eth_nft/index.ts
Change IPFS gateway for Astar NFT
> Change IPFS gateway for Astar NFT

- packages/extension-koni-ui/src/Popup/Sending/old/component/Static.tsx
- packages/extension-koni-ui/src/components/Dropdown.tsx
- packages/extension-koni-ui/src/components/Static.tsx
- packages/extension-koni-ui/src/components/Tooltip.tsx
- packages/extension-koni/manifest.json
- packages/extension-koni/package.json
- packages/extension-koni/public/background.html
- packages/extension-koni/public/index.html
- packages/extension-koni/public/notification.html
- packages/extension-koni/webpack.config.cjs
- packages/extension-koni/webpack.extension.cjs
- packages/extension-koni/webpack.shared.cjs
- packages/extension-koni/webpack.watch.cjs
- yarn.lock
**Related issue**
#80 
**What I do**
- Update webpack.config.js for split background into multi files.
- Changes background.js to background.html to load multi file.
> Split background.js and extension into multi file

- packages/extension-koni-base/src/api/predefineChainTokens.ts
**Related issues**
#201 
Add support ERC20 tokens of Moonfit on Moonbase
> Add support ERC20 tokens of Moonfit on Moonbase

- packages/extension-koni-base/build-cjs/api/endpoints.js
Update Centrifuge Parachain info #203
- provider: 'wss://centrifuge-parachain.api.onfinality.io/public-ws',
- genesisHash: '0xb3db41421702df9a7fcac62b53ffeac85f7853cc4e689e0b93aeb3db18c09d82',
> Update Centrifuge Parachain info #203

- packages/extension-koni-base/src/api/endpoints.ts
Update Centrifuge settings  #203
> update Centrifuge settings

- packages/extension-koni-base/src/background/handlers/State.ts
Pull request for task #212
update initial value for isShowBalances, accountAllLogo
> Update getSettings function in State.ts

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/index.tsx
- packages/extension-koni-ui/src/components/AccountInfo.tsx
- packages/extension-koni-ui/src/partials/Header/index.tsx
- yarn.lock
Pull request for task #191 
Update default avatar for all accounts:
Auto-generate account avatar: https://boringavatars.com/
> Update default avatar for all account

- packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalanceDetail/ChainBalanceDetail.tsx
- packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalances.tsx
- packages/extension-koni-ui/src/Popup/Home/index.tsx
Move back button to Chain Balance Detail screen
> Fix bug display incorrect screen when connection is lost

- packages/extension-koni-base/src/api/dotsama/registry.ts
- packages/extension-koni-base/src/background/handlers/State.ts
Fix a bug at custom EVM tokens when setting up chainRegistry
> Update issue 160

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Authorize/Request.tsx
- packages/extension-koni-ui/src/Popup/CreateAccount/Mnemonic.tsx
- packages/extension-koni-ui/src/Popup/CreateAccount/index.tsx
- packages/extension-koni-ui/src/Popup/Derive/SelectParent.tsx
- packages/extension-koni-ui/src/Popup/Derive/index.tsx
- packages/extension-koni-ui/src/Popup/ImportMetamaskPrivateKey/index.tsx
- packages/extension-koni-ui/src/Popup/ImportSeed/SeedAndPath.tsx
- packages/extension-koni-ui/src/Popup/ImportSeed/index.tsx
- packages/extension-koni-ui/src/Popup/RestoreJson.tsx
- packages/extension-koni-ui/src/messaging.ts
- Add a warning when wallet don't have any substrate account
- Add a checkbox in CreateAccount, ImportSeedPhrase, RestoreJson, DeriveAccount to auto connect to DApp
> Fix bug extension error when entering Substrate's seed phrase but selecting EVM account

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-ui/src/Popup/Settings/GeneralSetting.tsx
- packages/extension-koni-ui/src/components/View.tsx
- packages/extension-koni-ui/src/messaging.ts
- packages/extension-koni-ui/src/stores/Settings.ts
Update theme in expand view when change theme from popup view
> Fix bug do not update theme when change theme from popup view

- packages/extension-koni-ui/src/components/TokenDropdown/TokenItem.tsx
- packages/extension-koni-ui/src/components/View.tsx
fix bug init theme value equal undefined
fix UI Token Item
> Fix bug init theme value equal undefined, Update minor UI for Send fund

- packages/extension-koni-ui/src/Popup/CreateAccount/index.tsx
Pull request for task #192
fix bug hide Account in CreateAccount screen
> fix bug hide account in Create screen

- packages/extension-koni-ui/src/Popup/Accounts/Account.tsx
- packages/extension-koni-ui/src/Popup/Authorize/Request.tsx
- packages/extension-koni-ui/src/Popup/Metadata/Request.tsx
- packages/extension-koni-ui/src/Popup/Signing/Request/SignArea.tsx
- packages/extension-koni-ui/src/components/Toast/ToastProvider.tsx
- packages/extension-koni-ui/src/components/contexts.tsx
- packages/extension-koni-ui/src/hooks/useToast.tsx
- packages/extension-koni-ui/src/partials/Header/DetailHeader.tsx
Pull request for task #258
Fix bug Name in Home screen too long
Fix bug Cancel Button in Metadata, Signing, Authorize in LightTheme
Fix bug color of Toast
> Update some GUI

- packages/extension-koni-base/src/background/handlers/State.ts
Pull request for task #227  
Fix bug display multi popup connect wallet
> Fix bug display multi popup connect wallet

- packages/extension-koni-ui/src/Popup/Home/BalancesVisibility.tsx
- packages/extension-koni-ui/src/Popup/Home/index.tsx
Pull request for task #224
Update tooltip for show/hide balances
> Update Tooltip for show/hide balances

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/ImportMetamaskPrivateKey/MetamaskPrivateKeyImport.tsx
- packages/extension-koni-ui/src/Popup/ImportMetamaskPrivateKey/index.tsx
- packages/extension-koni-ui/src/messaging.ts
Pull request for task #208 
- Auto add '0x' to private key
- Show warning when use add seed phrase to private key input
> Update import Private key feature

- packages/extension-koni-ui/src/Popup/ImportMetamaskPrivateKey/MetamaskPrivateKeyImport.tsx
- packages/extension-koni-ui/src/Popup/ImportMetamaskPrivateKey/index.tsx
Pull request for task #208
Fix some GUI bug in ImportPrivateKey screen
> Fix some GUI bug in ImportPrivateKey screen

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/predefineChainTokens.ts
- packages/extension-koni-ui/src/Popup/Sending/AuthTransaction.tsx
- packages/extension-koni-ui/src/Popup/Sending/Donate.tsx
- packages/extension-koni-ui/src/Popup/Sending/SendFund.tsx
- packages/extension-koni-ui/src/Popup/Sending/utils.ts
- packages/extension-koni-ui/src/components/FormatBalance.tsx
- packages/extension-koni-ui/src/components/ReceiverDonateInputAddress.tsx
- packages/extension-koni-ui/src/components/ReceiverInputAddress.tsx
- packages/extension-koni-ui/src/components/SenderInputAddress.tsx
- packages/extension-koni-ui/src/components/TokenDropdown/Dropdown.tsx
- packages/extension-koni-ui/src/components/TokenDropdown/TokenItem.tsx
- packages/extension-koni-ui/src/components/TokenDropdown/index.tsx
- packages/extension-koni-ui/src/components/types.ts
- packages/extension-koni-ui/src/hooks/screen/home/useAccountBalance.ts
- packages/extension-koni-ui/src/util/chainBalancesApi.tsx
Pull request for #282 
Fix bug happens when select aUSD (Acala) to transfer
> Fix bug happens when select aUSD (Acala) to transfer

- packages/extension-koni-ui/src/Popup/Sending/AuthTransaction.tsx
- packages/extension-koni-ui/src/components/FormatBalance.tsx
- packages/extension-koni-ui/src/components/ReceiverDonateInputAddress.tsx
- packages/extension-koni-ui/src/components/ReceiverInputAddress.tsx
- packages/extension-koni-ui/src/components/TokenDropdown/index.tsx
- tsconfig.base.json
Relate to #282 
Some files related to #282 has wrong import.
This PR is for that problem
> Fix import issue of #282

- packages/extension-koni-base/src/api/nft/config.ts
- packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
- RMRK has removed block of the IPFS gateway
- Use dedicated IPFS gateway later
> Issue 289 - Fix rmrk ipfs gateway

- packages/extension-koni-ui/src/Popup/Home/TransactionHistory/TransactionHistory.tsx
> Fix error happens when deleted token

- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-base/src/background/handlers/Tabs.ts
Pull request for task #285 
Fix bug display 2 pop-up when connect to Astar Apps, Acala Apps,..
> Fix bug display 2 popup connect

- packages/extension-koni-base/src/api/endpoints.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
update SubSpace Testnet Endpoint
> update SubSpace Testnet Endpoint

- packages/extension-koni-base/src/api/endpoints.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
> update Subspace name

- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollectionPreview.tsx
> Minor bug on loading NFT collection preview

- packages/extension-koni-base/src/api/dotsama/transfer.ts
- packages/extension-koni-base/src/api/supportedCrossChains.ts
> Fix issue causes user cannot perform send fund/XCM transfer on Kintsugi chain

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> Update Darwinia Endpoint

- packages/extension-koni-base/src/background/handlers/Tabs.ts
> Fix chainId response from eth_chainId need to start with 0x value

- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-ui/src/Popup/Bonding/BondingNetworkSelection.tsx
- packages/extension-koni-ui/src/Popup/Bonding/BondingSubmitTransaction.tsx
- packages/extension-koni-ui/src/Popup/Bonding/BondingValidatorSelection.tsx
- packages/extension-koni-ui/src/Popup/Bonding/components/BondingAuthTransaction.tsx
- packages/extension-koni-ui/src/Popup/Bonding/components/UnbondingAuthTransaction.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/StakeAuthWithdrawal.tsx
- packages/extension-koni-ui/src/Popup/Settings/NetworkSettings/NetworkItem.tsx
- packages/extension-koni-ui/src/components/NetworkSelection/NetworkSelection.tsx
- packages/extension-koni-ui/src/components/NetworkSelection/NetworkSelectionItem.tsx
> Issue 375: Not showing crowdloan data properly

- packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmNft.tsx
- packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmToken.tsx
> Issue 375 + 380

- packages/extension-koni-base/src/api/bonding/index.ts
> Issue 382: Fix bug showing incorrect withdrawal time

- packages/extension-koni-base/src/api/bonding/ignore-relay-bonding.spec.ts
- packages/extension-koni-base/src/api/bonding/index.ts
- packages/extension-koni-base/src/api/staking/index.ts
- packages/extension-koni-base/src/background/subscription.ts
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingRow.tsx
> Koni/dev/issue 382 - Fix bug showing active stake and withdrawal amount

- packages/extension-koni-ui/src/components/AccountQrModal.tsx
> Fix bug can not scan QR from account (#394)

- packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmNft.tsx
- packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmToken.tsx
> #392: Fix bug import token

- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-ui/src/util/chainBalancesApi.tsx
- #145 
- Fix wrong balance in test network
- Detect network is test net from PREDEFINED_NETWORKS then ignore price for it
- No
- No
> [Issue-145] Account Balance still gets calculating from test net

- packages/extension-koni-base/src/api/coingecko.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
> fix imbue networkJson and bug when coingeckoPrice is null

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> update hydradx genesisHash

- packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
> Fix bug parsing JSON for RMRK NFT

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> Issue 421: Update litentry/litmus metadata

- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-ui/src/Popup/Settings/GeneralSetting.tsx
- packages/extension-koni-ui/src/components/themes.ts
**Related issues**
- #436 
- #331
> Disable auto trigger single mode, enable theme selection again.

- packages/extension-base/src/page/index.ts
- packages/extension-koni-ui/src/Popup/Signing/Request/SignArea.tsx
- packages/extension-koni-ui/src/Popup/Signing/Request/index.tsx
- packages/extension-koni/src/content.ts
**Related issue**
-#438 
-#327
> Fix logs from koni-content #438

- packages/extension-koni-ui/src/components/AccountQrModal.tsx
- packages/extension-koni-ui/src/components/Modal.tsx
- #425 
- Fix UI
- Fix UI
- No
- No
> [Issue-425] Fix UI

- packages/extension-koni-ui/src/components/AccountQrModal.tsx
- #425 
- Update UI/UX
- Update UI/UX
- No
- No
> [Issue-425] update UI/UX

- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollectionPreview.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
- packages/extension-koni-ui/src/components/Loading.tsx
- packages/extension-koni-ui/src/components/Spinner.tsx
> Update loading icon for NFTs

- packages/extension-koni/src/content.ts
> Add event interaction to EVM Provider Placeholder

- packages/extension-koni-ui/src/components/AccountInfo.tsx
> Fix EVM Account Identicon is not show

- packages/extension-koni-base/src/api/web3/defaultEvmToken.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-base/src/background/handlers/State.ts
> [Issue 490] Fix bug not allow adding default evm token when previously deleted

- packages/extension-koni-base/src/api/web3/defaultEvmToken.ts
- #517 
- Add MOONPETS NFT
-  Add MOONPETS NFT to `defaultEvmToken`
- No
- No
> [Issue-517] add MOONPETS NFT

- packages/extension-koni-base/src/background/handlers/State.ts
- #473 
- Fix show wrong account on the allow list by dApp type in case of upgrade version
- Fix show wrong account on the allow list by dApp type in case of upgrade version
- No
- No
> [Issue-473] Show wrong account on the allow list by dApp type in case of upgrade version

- packages/extension-koni-ui/src/util/index.ts
- #454 
- Support transaction history on Astar EVM
- Add `astarEvm` to `subscanByNetworkKey`
- No
- No
> [Issue-454] Support transaction history on Astar EVM

- packages/extension-koni-ui/src/Popup/Bonding/components/BondingAuthTransaction.tsx
> [Issue 550] Fix CSS on authorizing staking screen

- packages/extension-base/package.json
- packages/extension-koni-base/package.json
- yarn.lock
> [Issue-561] Bump version of @polkadot/phishing

- packages/extension-koni-ui/src/hooks/screen/home/useFetchStaking.ts
> [Issue 567] Staking data UI error

- packages/extension-koni-ui/src/Popup/Authorize/Request.tsx
> [Issue 570] Disable Connect button when there's no account

- packages/extension-koni-base/src/api/dotsama/balance.ts
> [Issue 576] Fix bug parsing Pangolin/Crab balance

- packages/extension-koni/src/content.ts
> Fix bug inject provider not auto remove

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue 605] Integrate Gear Testnet

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> Update default provider for Subspace gemini 1

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue 632] Update GM or Die End Point

- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-base/src/background/handlers/Tabs.ts
Web runner needs unsubscribe handle for messages have subscription.
This PR is for that.
> Update unsubscribe handle for messages 

- packages/extension-koni-ui/src/util/index.ts
> Add subspace subscan

- packages/extension-koni-base/src/api/nft/bit.country/index.ts
- packages/extension-koni-ui/src/Popup/Home/Nfts/api/paramsHandler.ts
> [Issue 654] Add owner attribute to Pioneer NFT

- packages/extension-koni-base/src/api/predefinedNetworks.ts
Update subspace block explorer
> [issue 651] Update subspace block explorer

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/bonding/astar.ts
- packages/extension-koni-base/src/api/bonding/paraChain.ts
- packages/extension-koni-base/src/api/bonding/relayChain.ts
- packages/extension-koni-base/src/api/nft/transfer.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Bonding/components/BondingAuthTransaction.tsx
- packages/extension-koni-ui/src/Popup/Bonding/components/UnbondingAuthTransaction.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/StakeAuthClaimReward.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/StakeAuthWithdrawal.tsx
> [Issue 648] Hot fix fee estimation error on NFT sending + staking

- packages/extension-koni-base/src/api/xcm/utils.ts
> [Issue 667] Temporarily disable Acala XCM

- packages/extension-koni-base/src/api/dotsama/transfer.ts
> [Issue 665] Support transfer for BIT token

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> Update Zeitgeist endpoints

- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-ui/src/Popup/Home/TransactionHistory/TransactionHistory.tsx
> [Issue 671] Update Zeitgeist price

- packages/extension-koni-base/src/api/bonding/index.ts
- packages/extension-koni-base/src/api/bonding/relayChain.ts
- packages/extension-koni-base/src/api/bonding/utils.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue 636] Add Ternoa Alphanet + Ternoa staking

- packages/extension-koni-ui/src/Popup/Home/Staking/StakeCompoundSubmitTransaction.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingMenu.tsx
> [Issue 520] Add comments and some optimizations

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue 697] Update network metadata

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/bonding/astar.ts
- packages/extension-koni-base/src/api/bonding/paraChain.ts
- packages/extension-koni-base/src/api/bonding/relayChain.ts
> [Issue 706] Add raw fee info to staking functions

- packages/extension-koni-base/src/api/bonding/paraChain.ts
- packages/extension-koni-base/src/api/bonding/utils.ts
> [Issue 710] Add default option in case no information of parachain inflation

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/bonding/astar.ts
- #720
- Add `icon` for `DelegationItem`
- Add `icon` for `DelegationItem`
- No
- No
> [Issue-720] [DelegationItem] add icon

- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-ui/src/assets/logo/index.ts
- packages/extension-koni-ui/src/util/index.ts
> Add support Snow Network (#734)

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/web-runner/src/fallback.ts
- Add message for updating current account
- Fix issue that causes unnecessary loops when getting data from local storage
> Related to web runner performance

- packages/extension-koni-ui/src/partials/AccountMenuSettings.tsx
- packages/extension-koni-ui/src/partials/Header/index.tsx
> [Issue 752] Adding KeyStone branding

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/background/handlers/Mobile.ts
Add ping check message for mobile
> Add ping check message for mobile

- packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
- #759
- Fix error when chain not selected
- Fix error when chain not selected
- No
- No
> [Issue-759] Unable to send NFT with QR Account in case of network not selected

- packages/extension-koni-base/src/api/bonding/paraChain.ts
- packages/extension-koni-base/src/api/bonding/relayChain.ts
- packages/extension-koni-base/src/api/bonding/utils.ts
> [Issue 770] Fix number overflow on staking information

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue 775] Update endpoint for Amplitude

- packages/extension-koni-ui/src/Popup/Home/Nfts/api/transferHandler.ts
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollection.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItemPreview.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/TransferNftContainer.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/utils.ts
> [Issue 777] Remove old interfaces of NFT code

- packages/extension-koni-base/src/background/handlers/Tabs.ts
> [Issue-783] Fix error with EVM Provider because https rpc 

- packages/extension-koni-base/src/api/coingecko.ts
> [Issue 785] Update price for KBTC

- packages/extension-koni-base/src/api/nft/nft.ts
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
> [Issue 794] Bug parsing IPFS link

- packages/extension-koni-base/src/background/cron.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- Fix issue that causes networkMap store subject fires many times
- Fix issue about wrong used gas calculation
> Fix some issues 

- package.json
- packages/extension-koni-base/src/api/nft/nft.ts
- packages/extension-koni-base/src/background/cron.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-base/src/background/webRunnerCron.ts
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
Fix issue that causes networkMap store subject fires many times for Web runner
> Fix issue that causes networkMap store subject fires many times for Web runner

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue 801] Support staking for Shiden

- packages/extension-koni-base/src/api/bonding/relayChain.ts
> [Issue 809] Fix bug withdrawing stake with slashing spans

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/dotsama/shared/signAndSendExtrinsic.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
- packages/extension-koni-ui/src/contexts/ScannerContext.tsx
- #735
- [EVM] Fix invalid signature
- [EVM] Fix invalid signature
- No
- No
> [Issue-735] Refactor Interface Sign Request

- packages/extension-koni-ui/src/contexts/ScannerContext.tsx
- packages/extension-koni-ui/src/util/getNetworkJsonByGenesisHash.ts
- #838
- Update qr scanner
- Update qr scanner
- No
- No
> [Issue-838] Can not sign the Claim reward transaction with QR-signer account

- packages/extension-koni-ui/src/Popup/Bonding/BondingSubmitTransaction.tsx
> [Issue 845] Fix bug navigating after staking

- packages/extension-koni-base/src/api/bonding/relayChain.ts
- packages/extension-koni-ui/src/Popup/Bonding/UnbondingSubmitTransaction.tsx
> [Issue 804] Fix bug parsing number on unstaking

- packages/extension-koni-base/src/api/dotsama/crowdloan.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-base/src/migration/scripts/RemoveWrongCrowdloan.ts
- packages/extension-koni-base/src/migration/scripts/index.ts
- packages/extension-koni-ui/src/Popup/ExternalRequest/QRScanner/index.tsx
> [Issue-865] Remove EVM crowdloan record

- packages/extension-koni-base/src/api/nft/wasm_nft/utils.ts
- packages/extension-koni-base/src/api/tokens/wasm/defaultWasmToken.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-base/src/db-stores/Nft.ts
- packages/extension-koni-base/src/db-stores/NftCollection.ts
- packages/extension-koni-base/src/services/DatabaseService.ts
> [Issue 864] Fix bug duplicating NFT collection on genesisHash change

- packages/extension-koni-ui/src/Popup/ExternalRequest/SignQR/index.tsx
- packages/extension-koni-ui/src/contexts/ScannerContext.tsx
- packages/extension-koni-ui/src/partials/Header/SubHeader.tsx
- #871
- Fix remember password evm account after use sign stake action
- Fix remember password evm account after use sign stake action
- No
- No
> [Issue-871] fix remember password evm account after use sign stake action

- packages/extension-koni-ui/src/Popup/Home/Staking/StakingMenu.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingRow.tsx
> [Issue 867] Fix UI bug claiming reward for Amplitude

- packages/extension-koni-base/src/api/predefinedNetworks.ts
- #859
- Update Aleph Zero Testnet genesisHash
- Update Aleph Zero Testnet genesisHash
- No
- No
> [Issue-859] [Substrate] Update function parse transaction

- packages/extension-koni-ui/src/Popup/Signing/Request/index.tsx
- packages/extension-koni-ui/src/contexts/ScannerContext.tsx
- packages/extension-koni-ui/src/util/scanner/decoders.ts
- #890
- Update message network not active
- Update default network qr-payload with message
- Update message network not active
- Update default network qr-payload with message
- No
- No
> [Issue-890] Update default network for sign message request

- packages/extension-koni-ui/src/contexts/ScannerContext.tsx
> Wrong signature when signing raw with QR Signer account

- packages/extension-koni-ui/src/Popup/ImportLedger.tsx
- packages/extension-koni-ui/src/Popup/Sending/SendFund.tsx
> Handle case attach and send asset for Ledger account with addess index #0

- packages/extension-koni-base/src/api/nft/config.ts
> Update RMRK NFT endpoints

- packages/extension-koni-ui/src/constants/strings.ts
- packages/extension-koni-ui/src/contexts/ScannerContext.tsx
- packages/extension-koni-ui/src/util/scanner/decoders.ts
> Update message when scan QR code with QR signer account in case the account does not exist

- packages/extension-koni-base/src/api/bonding/amplitude.ts
> [Issue 914] Add incrementDelegatorRewards call

- packages/extension-koni-base/src/api/dotsama/balance.ts
> [Issue 916] Temporary fix free balance for kusama

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-koni-base/src/api/staking/subqueryStaking.ts
- packages/extension-koni-base/src/background/handlers/State.ts
- packages/extension-koni-base/src/background/subscription.ts
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingRow.tsx
- packages/extension-koni-ui/src/stores/StakingReward.ts
- packages/extension-koni-ui/src/stores/types.ts
> [Issue 907] Fix bug duplicating staking reward records

- packages/extension-koni-base/src/api/coingecko.ts
> Update price for iBTC

- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollectionPreview.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItemPreview.tsx
> Fix bug do not show sub0 Lisbon 2022 NFT

- packages/extension-koni-ui/src/Popup/Attach/AttachReadOnly.tsx
- packages/extension-koni-ui/src/partials/AccountMenuSettings.tsx
> Update "readonly account" to "read-only account"

- packages/extension-koni-base/src/api/bonding/paraChain.ts
> Update APR for Turing Network

- packages/extension-koni-base/src/api/predefinedNetworks.ts
> [Issue-977] Update endpoints

- packages/extension-koni-base/src/api/dotsama/balance.ts
> [Issue-975] Update Equilibrium balance structure

- packages/extension-koni-base/src/api/dotsama/balance.ts
> [Issue 981] Update logic getting balance for multiple accounts

- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-ui/src/util/index.ts
> Update coingeckoKey for Nodle network

- packages/extension-koni-base/src/api/nft/wasm_nft/index.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-base/src/api/tokens/index.ts
- packages/extension-koni-base/src/api/tokens/wasm/helper/index.ts
- packages/extension-koni-base/src/api/tokens/wasm/helper/shiden_psp34_demo.json
- packages/extension-koni-base/src/api/tokens/wasm/index.ts
- packages/extension-koni-base/src/api/tokens/wasm/utils.ts
- packages/extension-koni-base/src/background/handlers/Extension.ts
> [Issue-985] Update support for Shiden base PSP-34 token

- packages/extension-koni-base/src/api/dotsama/crowdloan.ts
- packages/extension-koni-base/src/migration/scripts/RemoveWrongCrowdloan.ts
- packages/extension-koni-base/src/migration/scripts/index.ts
> [Issue-991] Fix duplicate crowdloan problems

- packages/extension-koni-base/src/api/nft/config.ts
- packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
> [Issue-963] update parsing RMRK NFTs

- packages/extension-koni-base/src/api/bonding/relayChain.ts
- packages/extension-koni-base/src/api/bonding/utils.ts
> [Issue-997] update Aleph Zero validator APR

- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Tokens/index.tsx
- packages/extension-koni-ui/src/Popup/Root.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/components/Layout/Home.tsx
- packages/extension-koni-ui/src/components/Layout/index.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SelectedAccount.tsx
- packages/extension-koni-ui/src/components/Main.tsx
- packages/extension-koni-ui/src/components/index.ts
- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
> [Issue-1025] Update home layout

- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/components/EmptyList.tsx
- packages/extension-koni-ui/src/hooks/screen/crowdloan/useGetCrowdloanList.ts
- packages/extension-koni-ui/src/hooks/screen/home/useAccountBalance.ts
- packages/extension-koni-ui/src/types/crowdloan.ts
> Update UI - Crowdloan Screen

- packages/extension-koni-ui/src/Popup/Debugger/DebuggerMenu.tsx
- packages/extension-koni-ui/src/Popup/PhishingDetected.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
> Update UI for Phishing Screen

- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
- packages/extension-koni-ui/src/components/MetaInfoBlock.tsx
- packages/extension-koni-ui/src/components/Modal/FilterModal.tsx
- packages/extension-koni-ui/src/hooks/modal/useFilterModal.ts
- packages/extension-koni-ui/src/hooks/modal/useLazyList.ts
> Update UI for Staking feature

- packages/extension-koni-ui/src/Popup/Home/Staking/MoreActionModal.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
- packages/extension-koni-ui/src/Popup/Transaction/Stake.tsx
- packages/extension-koni-ui/src/Popup/Transaction/Transaction.tsx
- packages/extension-koni-ui/src/Popup/Transaction/Unstake.tsx
- packages/extension-koni-ui/src/Popup/Transaction/parts/BondedBalance.tsx
- packages/extension-koni-ui/src/Popup/Transaction/parts/FreeBalance.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/components/Account/Info/AvatarGroup.tsx
- packages/extension-koni-ui/src/components/Field/AmountInput.tsx
- packages/extension-koni-ui/src/components/Field/MultiValidatorSelector.tsx
- packages/extension-koni-ui/src/components/Field/PoolSelector.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/components/Field/ValidatorSelector.tsx
- packages/extension-koni-ui/src/components/ScreenTab.tsx
- packages/extension-koni-ui/src/components/SelectValidatorInput.tsx
- packages/extension-koni-ui/src/components/StakingItem/StakingValidatorItem.tsx
- packages/extension-koni-ui/src/hooks/modal/useSelectValidators.ts
> Update UI for MultiValidatorSelector

- .eslintrc.js
- packages/extension-koni-base/src/api/dotsama/api.ts
- packages/extension-koni-base/src/api/dotsama/balance.ts
- packages/extension-koni-base/src/api/dotsama/transfer.ts
- packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
- packages/extension-koni-base/src/api/nft/wasm_nft/index.ts
- packages/extension-koni-base/src/api/predefinedNetworks.ts
- packages/extension-koni-base/src/api/tokens/wasm/defaultWasmToken.ts
- packages/extension-koni-base/src/api/tokens/wasm/helper/psp22_abi.json
- packages/extension-koni-base/src/api/tokens/wasm/helper/psp34_abi.json
- packages/extension-koni-base/src/api/tokens/wasm/index.ts
- packages/extension-koni-base/src/api/tokens/wasm/utils.ts
> [Issue 1095] Update logic for ink! 4.0

- packages/extension-koni-base/src/api/nft/wasm_nft/index.ts
- packages/extension-koni-base/src/api/nft/wasm_nft/utils.ts
> [Issue 1112] Add ArtZero API

- packages/extension-koni-base/src/api/dotsama/balance.ts
- packages/extension-koni-base/src/api/tokens/wasm/utils.ts
> [Issue 1118] fix bug parsing psp22 token

- packages/extension-koni-base/src/api/predefinedNetworks.ts
Related issue: https://github.com/Koniverse/SubWallet-Extension/issues/1117
> Update Azero block explorer

- packages/extension-base/src/koni/api/dotsama/balance.ts
- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
- packages/extension-base/src/koni/api/nft/wasm_nft/utils.ts
- packages/extension-base/src/koni/api/tokens/wasm/index.ts
- packages/extension-base/src/koni/api/tokens/wasm/utils.ts
- packages/extension-base/src/services/chain-service/handler/SubstrateChainHandler.ts
- packages/extension-base/src/services/chain-service/helper/psp22_abi.json
- packages/extension-base/src/services/chain-service/helper/psp34_abi.json
- packages/extension-koni-ui/src/Popup/Settings/Tokens/TokenDetail.tsx
> [Issue 1144] update ink! 4.0 for PSP-22 and PSP-34

- packages/extension-koni-ui/src/Popup/Home/Staking/MoreActionModal.tsx
- packages/extension-koni-ui/src/Popup/Transaction/Transaction.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Withdraw.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/components/Field/AmountInput.tsx
- packages/extension-koni-ui/src/constants/transak.ts
- #1150 
- Add Withdraw screen
- Add Withdraw screen
- No
- No
> [Issue-1150] Upgrade UI - Implement Withdraw feature for the "All accounts" mode 

- packages/extension-koni-ui/src/Popup/Confirmations/index.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/parts/ConfirmationHeader.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/Transaction/index.tsx
- #1157
- Update UI
- Update UI
- No
- No
> [Issue-1157] Upgrade UI - Update UI confirmation screen follow by design

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/history-service/index.ts
- packages/extension-base/src/services/transaction-service/index.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendNFT.tsx
- packages/extension-koni-ui/src/components/Field/AddressInput.tsx
- #1155
- Update component AddressInput
- Update component AddressInput
- No
- No
> [Issue-1155] Upgrade UI - Keep the address inputted by the user

- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
- #1152
- Update error style
- Update error style
- No
- No
> [Issue-1152] Upgrade UI - Update style of the error message in some screens

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- #1140
- Update validate value field
- Update validate value field
- No
- No
> [Issue-1140] Upgrade UI - Bugs related to the send tokens feature

- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/components/Field/MultiValidatorSelector.tsx
- packages/extension-koni-ui/src/components/Field/PoolSelector.tsx
- packages/extension-koni-ui/src/components/Modal/SortingModal.tsx
- packages/extension-koni-ui/src/components/Modal/Staking/StakingNetworkDetailModal.tsx
- #1176
- Update UI
- Update UI
- No
- No
> [Issue-1176] Upgrade UI - Some issues related to the Staking feature 

- packages/extension-koni-ui/src/Popup/Account/RestoreJson.tsx
- packages/extension-koni-ui/src/Popup/Keyring/ApplyMasterPassword/index.tsx
- packages/extension-koni-ui/src/Popup/Root.tsx
- #1139
- Fix flash after import JSON (multiple account)
- Fix flash after import JSON (multiple account)
- No
- No
> [Issue-1139] UpgradeUI - Show counter of accounts to which the master password needs to be applied is incorrect

- packages/extension-koni-ui/src/Popup/Home/History/Detail/index.tsx
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/components/Field/MultiValidatorSelector.tsx
- packages/extension-koni-ui/src/components/Field/PoolSelector.tsx
- packages/extension-koni-ui/src/components/Modal/AccountSelectorModal.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/TokensSelectorModal.tsx
- packages/extension-koni-ui/src/components/Modal/SortingModal.tsx
- packages/extension-koni-ui/src/components/Modal/Staking/ValidatorDetailModal.tsx
- packages/extension-koni-ui/src/components/StakingItem/SwStakingItem.tsx
- packages/extension-koni-ui/src/constants/modal.ts
- packages/extension-koni-ui/src/hooks/modal/useFilterModal.ts
- packages/extension-koni-ui/src/hooks/screen/home/useReceiveQR.ts
- #1175
- Handle reset filter and sort
- Handle reset filter and sort
- No
- No
> [Issue-1175] Upgrade UI - UI Bugs related to staking feature

- packages/extension-koni-ui/src/Popup/Keyring/ApplyMasterPassword/index.tsx
- packages/extension-koni-ui/src/Popup/Root.tsx
- #1193
- Stand on migrate done after migrate
- Stand on migrate done after migrate
- No
- No
> [Issue-1193] Upgrade UI - Do not show the Successful screen after migrated password successfully

- packages/extension-koni-ui/src/Popup/Settings/Security/ManageWebsiteAccess/index.tsx
- #1198
- Fallback error when search
- Fallback error when search
- No
- No
> [Issue-1198] Error page when search network in Manage website access

- packages/extension-koni-ui/src/components/Field/AccountSelector.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/index.tsx
- packages/extension-koni-ui/src/components/Modal/Customize/CustomizeModalContent.tsx
- packages/extension-koni-ui/src/utils/account/account.ts
- #1196
- Add sort func
- Add sort func
- No
- No
> [Issue-1196] Upgrade UI - apply sort for some list

- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
- packages/extension-koni-ui/src/Popup/Settings/Security/ManageWebsiteAccess/index.tsx
- #1216
- Fix not save collection name
- Fix not save collection name
- No
- No
> [Issue-1216] Do not save Collection name input when import NFT

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/koni/background/handlers/Tabs.ts
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-base/src/services/chain-service/types.ts
- packages/extension-base/src/services/history-service/index.ts
- packages/extension-koni-ui/src/Popup/Confirmations/index.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/AddNetworkConfirmation.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/AddTokenConfirmation.tsx
Related issues:
- #1241
- #1247
- #1242
> [Issue-1241+1242] Fix EVM DApp problems + some small issue

- packages/extension-base/src/koni/api/nft/acala_nft/index.ts
- packages/extension-base/src/koni/api/nft/bit.country/index.ts
- packages/extension-base/src/koni/api/nft/evm_nft/index.ts
- packages/extension-base/src/koni/api/nft/index.ts
- packages/extension-base/src/koni/api/nft/karura_nft/index.ts
- packages/extension-base/src/koni/api/nft/nft.ts
- packages/extension-base/src/koni/api/nft/rmrk_nft/index.ts
- packages/extension-base/src/koni/api/nft/statemine_nft/index.ts
- packages/extension-base/src/koni/api/nft/unique_nft/index.ts
- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/storage-service/DatabaseService.ts
- packages/extension-base/src/services/storage-service/db-stores/Nft.ts
> [Issue 1235] Update cleaning up NFTs after fetching

- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/hooks/screen/common/useFetchChainAssetInfo.ts
> [Issue 1231] Fix bug not fetching validators when chain state change

- packages/extension-koni-ui/src/hooks/screen/home/useReceiveQR.ts
- #1240
- Filter token for ledger account
- Filter token for ledger account
- No
- No
> [Issue-1240] Need to display address list by token that Ledger account supports when receiving Ledger account address with "All accounts" mode

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/assets/logo/index.ts
- yarn.lock
> [Issue-1272] Handle case big number by updating @subwallet/react-ui

- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
- packages/extension-koni/public/index.html
- packages/extension-koni/public/main.css
> [Issue-1275] Fix border problems some case like full screen modal

- packages/extension-koni-ui/src/constants/transak.ts
- #1317
- Add NEER token
- Add NEER token
- No
- No
> [Issue-1317] Add support for $NEER on Transak

- packages/extension-base/src/koni/api/staking/bonding/amplitude.ts
- packages/extension-base/src/services/chain-service/index.ts
> [Issue 1319] Fix bug timeout fetching latest data

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-koni-ui/src/hooks/chain/useAssetChecker.tsx
- #1289
- Add auto active native token
- Add auto active native token
- No
- No
> [Issue-1289] Enable native token automatically when enabling local token from the transfer screen

- packages/extension-base/src/services/migration-service/scripts/MigrateAuthUrls.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- #1301
- Fix StellaSwap connect
- Fix StellaSwap connect
- No
- No
> [Issue-1301] Do not automatically switch the network according to the dApp in case of version upgrade

- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailList.tsx
- packages/extension-koni-ui/src/Popup/Home/Tokens/index.tsx
- #1336
- Fix UI bug when scroll
- Fix UI bug when scroll
- No
- No
> [Issue-1336] UI bug when scroll wallet

- packages/extension-base/src/koni/background/handlers/Extension.ts
> [Issue 1353] fix bug setting currentAccount upon bulk account import

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Account/AccountDetail.tsx
- packages/extension-koni-ui/src/Popup/Account/AccountExport.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/ReceiveQrModal.tsx
- patches/react-qrcode-logo+2.9.0.patch
- yarn.lock
- #1382
- Update new QRCode style
- Update new QRCode style
- No
- No
> [Issue-1382] Update the style of the QR code

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/transaction-service/utils.ts
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/assets/logo/index.ts
- yarn.lock
- #1381
- Update explorer for some chain
- Update explorer for some chain
- No
- No
> [Issue-1381] Add support "view transaction explorer" for the some chain

- packages/extension-koni-ui/src/Popup/Account/ImportPrivateKey.tsx
- #1395
- Fix not auto add prefix
- Fix not auto add prefix
- No
- No
> [Issue-1395] Do not import private key when exported from MetaMask

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
- packages/extension-koni-ui/src/Popup/Account/ConnectQrSigner/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/components/Field/MultiValidatorSelector.tsx
- packages/extension-koni-ui/src/components/Modal/RequestCameraAccessModal.tsx
- packages/extension-koni-ui/src/components/SelectValidatorInput.tsx
> [Issue 1396] fix bug showing minimum join pool amount

- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
> [Issue 1392] fix bug parsing nominations on staking screen

- packages/extension-base/src/services/storage-service/DatabaseService.ts
- packages/extension-base/src/services/storage-service/db-stores/Nft.ts
> [Issue 1404] fix bug showing EVM NFTs

- .github/workflows/push-koni-dev.yml
- scripts/koni-ci-build-dev.mjs
> Add web runner deployment

- packages/extension-base/src/services/transaction-service/index.ts
Related issue:
- #1472 
- https://github.com/Koniverse/SubWallet-Mobile/issues/722
> [Issue-1472] Update web runner for fix ABI block explorer on mobile

- packages/extension-base/src/services/chain-service/utils.ts
- #1451 
- Fix error when choose send token from custom network
- Fix error when choose send token from custom network
- No
- No
> [Issue-1451] Error page when send token of the custom network

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendNFT.tsx
- packages/extension-koni-ui/src/components/Field/AddressInput.tsx
- packages/extension-koni-ui/src/components/Modal/AddressBook/AddressBookModal.tsx
- packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
- #1454
- Handle case send to ledger account
- Handle case send to ledger account
- No
- No
> [Issue-1454] Do not show Ledger account in "My Wallet" list when sending tokens that Ledger acc does not support

- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-base/src/services/chain-service/constants.ts
> [Issue 1108] update calculating staking APR for Ternoa

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/transaction-service/index.ts
- #1492
- Update logic check balance
- Update logic check balance
- No
- No
> [Issue-1492] Re-check send fund ERC20 token Polygon

- packages/extension-base/src/services/transaction-service/helpers/index.ts
- packages/extension-base/src/services/transaction-service/index.ts
- #1385
- Update notification in case transaction time out
- Update notification in case transaction time out
- No
- No
> [Issue-1385] Update notification in case transaction time out

- packages/extension-koni-ui/src/Popup/Settings/Tokens/FungibleTokenImport.tsx
- packages/extension-koni-ui/src/components/Field/AddressInput.tsx
- packages/extension-koni-ui/src/components/Field/Base.tsx
- packages/extension-koni-ui/src/hooks/chain/useChainChecker.tsx
- #1419
- Update UI
- Update UI
- No
- No
> [Issue-1419] Update some screens follow by design

- packages/extension-base/src/koni/api/xcm/index.ts
- packages/extension-base/src/koni/api/xcm/polkadotXcm.ts
> [Issue 1352] update params for XCM on Astar

- packages/extension-base/src/services/transaction-service/index.ts
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- #1499
- Fix UI
- Fix UI
- No
- No
> [Issue-1499] Don't show send history in case xcm on same account

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/transaction-service/types.ts
- #1505
- Fix error on Firefox
- Fix error on Firefox
- No
- No
> [Issue-1505] Error page when perform xcm on Firefox browser

- packages/extension-koni-ui/src/Popup/Confirmations/variants/AuthorizeConfirmation.tsx
- packages/extension-koni-ui/src/Popup/Settings/Security/ManageWebsiteAccess/Detail.tsx
- packages/extension-koni-ui/src/components/Layout/parts/ConnectWebsiteModal.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/index.tsx
- #1225
- Allow watch-only account connect dApp
- Allow watch-only account connect dApp
- No
- No
> [Issue-1225] Allow DApp access to read-only account

- packages/extension-koni-ui/src/Popup/Transaction/parts/FreeBalance.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/components/Field/ChainSelector.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/components/Modal/Customize/CustomizeModal.tsx
> [Issue-1509] Update send fund layout

- packages/extension-base/src/services/chain-service/constants.ts
- #1522
- Fix transfer on bifrost_dot
- Fix transfer on bifrost_dot
- No
- No
> [Issue-1522] Do not transfer BNC (Bifrost Polkadot)

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue 1526] update chain-list

- packages/extension-base/src/koni/api/staking/bonding/paraChain.ts
- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
- packages/extension-base/src/koni/api/staking/bonding/utils.ts
> [Issue 1538] fix bug parsing identity pallet for Calamari

- packages/extension-base/src/koni/background/handlers/Extension.ts
- #1524
- Remove add contact when create transaction
- Remove add contact when create transaction
- No
- No
> [Issue-1524] Show incorrect address book type

- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailUpperBlock.tsx
- packages/extension-koni-ui/src/Popup/Home/Tokens/UpperBlock.tsx
- #1531
- Update icon
- Update icon
- No
- No
> [Issue-1531] Update Receive icon to Copy icon on Homepage screen

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/chain-service/helper/api-helper/spec/dataavail.ts
- packages/extension-base/src/services/chain-service/helper/api-helper/spec/index.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-1541] Update chain-list

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/xcm/polkadotXcm.ts
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/koni/api/xcm/xcmPallet.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue 1546] Update XCM parsing

- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
> [Issue 1508] update detecting on-chain attributes for WASM NFTs

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/migration-service/scripts/MigrateEthProvider.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-1576] Update chainlist (w26)

- packages/extension-base/src/koni/api/xcm/polkadotXcm.ts
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/services/transaction-service/xcm.spec.ts
- #1579
- Update XCM for Astar, Interlay, HydraDX
- Update XCM for Astar, Interlay, HydraDX
- No
- No
> [Issue-1579] Update XCM for Astar, Interlay, HydraDX

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/components/Field/AddressInput.tsx
- #1559
- Fix bugs related to address book
- Fix bugs related to address book
- No
- No
> [Issue-1559] Bugs related to address book

- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- yarn.lock
> [Issue-1590] Update chainlist (w27)

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/api/nft/config.ts
- packages/extension-base/src/utils/environment.ts
- packages/extension-base/src/utils/index.ts
> [Issue-1602] NFT Gateway problems with non-extension environment

- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/ClaimReward.tsx
- #1475
- Update UI
- Update UI
- No
- No
> [Issue-1475] Some UI validation when performing staking operations

- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
> [Issue 1350] Update controller params for relaychain staking

- packages/extension-base/src/koni/api/staking/bonding/astar.ts
- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/Withdraw.tsx
> [Issue 1557] update logic calculating withdrawable amount

- packages/extension-base/src/koni/api/staking/bonding/astar.ts
- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/Withdraw.tsx
Reverts Koniverse/SubWallet-Extension#1612
> Revert "[Issue 1557] update logic calculating withdrawable amount"

- packages/extension-base/src/koni/api/nft/acala_nft/index.ts
- packages/extension-base/src/koni/api/nft/bit.country/index.ts
- packages/extension-base/src/koni/api/nft/evm_nft/index.ts
- packages/extension-base/src/koni/api/nft/index.ts
- packages/extension-base/src/koni/api/nft/karura_nft/index.ts
- packages/extension-base/src/koni/api/nft/nft.ts
- packages/extension-base/src/koni/api/nft/rmrk_nft/index.ts
- packages/extension-base/src/koni/api/nft/statemine_nft/index.ts
- packages/extension-base/src/koni/api/nft/unique_nft/index.ts
- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/koni/background/subscription.ts
- packages/extension-base/src/services/storage-service/DatabaseService.ts
- packages/extension-base/src/services/storage-service/db-stores/Nft.ts
> [Issue 1615] update reload NFTs

- packages/extension-koni-ui/src/Popup/Account/ImportPrivateKey.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/AuthorizeConfirmation.tsx
- packages/extension-koni-ui/src/Popup/Settings/Chains/ManageChains.tsx
- packages/extension-koni-ui/src/components/Account/Info/AvatarGroup.tsx
- packages/extension-koni-ui/src/components/Modal/Customize/CustomizeModalContent.tsx
- #1548 
- Update UI
- Update UI
- No
- No
> [Issue-1548] UI bugs

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/setting-service/constants.ts
- packages/extension-koni-ui/src/Popup/Settings/GeneralSetting.tsx
- packages/extension-koni-ui/src/components/Modal/Customize/CustomizeModal.tsx
- packages/extension-koni-ui/src/messaging.ts
- packages/extension-koni-ui/src/stores/base/Settings.ts
- packages/extension-koni-ui/src/stores/utils/index.ts
- #1243
- Synchronize UI settings between tabs
- Synchronize UI settings between tabs
- No
- No
> [Issue-1243] Sync configuration between expand view and popup view

- packages/extension-koni-ui/src/Popup/WalletConnect/ConnectionDetail.tsx
- packages/extension-koni-ui/src/components/Field/AddressInput.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
- #1507
- Update UI for Firefox
- Update UI for Firefox
- No
- No
> [Issue-1507] UI bugs on the Firefox browser

- packages/extension-koni-ui/src/Popup/WalletConnect/ConnectionDetail.tsx
- packages/extension-koni-ui/src/components/Modal/SortingModal.tsx
- #1634
- Update icon font weight
- Update icon font weight
- No
- No
> [Issue-1634] Criteria's icon on the Sorting pool/validator/collator/dApp screen is incorrect

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/transaction-service/xcm.spec.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue 1620] Upgrade chain-list

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Home/Nfts/component/NftGalleryWrapper.tsx
- yarn.lock
- #1651
- Fix display video
- Fix display video
- No
- No
> [Issue-1651] Fix Video NFT size

- packages/extension-koni-ui/src/utils/common/date.ts
- #1654
- Fix function display time
- Fix function display time
- No
- No
> [Issue-1654] Show incorrect transaction time on the History

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftCollections.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
- yarn.lock
> [Issue-1661] Update chainlist (w29)

- packages/extension-koni-ui/src/Popup/Settings/Tokens/component/TokenItemFooter.tsx
- packages/extension-koni-ui/src/components/ChainItemFooter.tsx
- #1633
- Fix sync configuration of the network and token
- Fix sync configuration of the network and token
- No
- No
> [Issue-1633] Sync configuration of the network and token

- packages/extension-base/src/services/transaction-service/index.ts
- #1667
- Fix validate transfer LINK token
- Fix validate transfer LINK token
- No
- No
> [Issue-1667] Re-check validate in case Sender available balance = 0

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-1708] Update chainlist (w30)

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/koni/background/handlers/Tabs.ts
- packages/extension-base/src/page/Accounts.ts
- packages/extension-base/src/page/Injected.ts
- packages/extension-base/src/services/request-service/handler/AuthRequestHandler.ts
- packages/extension-base/src/services/request-service/index.ts
> [Issue-1712] Allow DApp subscribe accounts list

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/api/nft/config.ts
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- packages/extension-koni-ui/src/components/MetaInfo/parts/AccountItem.tsx
- packages/extension-koni-ui/src/hooks/screen/staking/useGetAccountsByStaking.ts
- packages/extension-koni/public/locales/en/translation.json
- packages/extension-koni/public/locales/ja/translation.json
- packages/extension-koni/public/locales/vi/translation.json
- packages/extension-koni/public/locales/zh/translation.json
> [Issue 1643] fix bug showing staking accounts

- packages/extension-koni-ui/src/Popup/Transaction/helper/staking/stakingHandler.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/components/Account/EmptyValidator.tsx
- packages/extension-koni-ui/src/components/Account/index.tsx
- packages/extension-koni-ui/src/components/Field/MultiValidatorSelector.tsx
- packages/extension-koni-ui/src/components/Field/PoolSelector.tsx
- packages/extension-koni-ui/src/constants/stakingStatusUi.ts
- packages/extension-koni/public/locales/en/translation.json
- packages/extension-koni/public/locales/ja/translation.json
- packages/extension-koni/public/locales/vi/translation.json
- packages/extension-koni/public/locales/zh/translation.json
> [Issue 1496] Do not show validator on the Select validator screen in case turn on network when stake

- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
> [Issue 1721] reset selected validators

- packages/extension-base/src/koni/background/handlers/Extension.ts
- #1731
- Fix still show histories of deleted account
- Fix still show histories of deleted account
- No
- No
> [Issue-1731] Still show history of the removed account #1731

- packages/extension-base/src/koni/background/handlers/Extension.ts
- #1748
- Fix bug history
- Fix bug history
- No
- No
> [Issue-1748] Do not display the history of addresses other than the original address

- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/components/Field/MultiValidatorSelector.tsx
- #1757
- Fix infinity change value
- Fix infinity change value
- No
- No
> [Issue-1757] Validator avatars are auto-generated continuously

- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
> [Issue 1752] fix bug showing chain minimum active stake

- packages/extension-koni-ui/src/Popup/Home/Nfts/NftItemDetail.tsx
> [Issue 1784] show NFT ID and collection ID

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/constants/buy/banxa.ts
- packages/extension-koni-ui/src/utils/buy/banxa.ts
- yarn.lock
- #1760
- Change way to use Banxa service
- Change way to use Banxa service
- No
- No
> [Issue-1760] Webapp - Can not buy token from Banxa

- packages/extension-base/src/services/wallet-connect-service/index.ts
- #1806
- Improve case reset account
- Improve case reset account
- No
- No
> [Issue-1806] Improve case delete connection when reset wallet

- packages/extension-base/src/koni/api/nft/acala_nft/index.ts
- packages/extension-base/src/koni/api/nft/karura_nft/index.ts
- packages/extension-base/src/koni/api/nft/nft.ts
- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
- packages/extension-base/src/koni/api/tokens/wasm/index.ts
- packages/extension-base/src/services/chain-service/helper/azero_domain_registry_abi.json
- packages/extension-base/src/services/chain-service/helper/index.ts
- packages/extension-base/src/services/chain-service/helper/pink_psp34_abi.json
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
- packages/extension-koni-ui/src/Popup/Settings/Tokens/FungibleTokenImport.tsx
> [Issue 1817] Fix a few bugs with NFT

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/dotsama/domain.ts
- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue 1821] update chain-list

- packages/extension-koni/webpack.shared.cjs
- packages/extension-koni/webpack.watch.cjs
- #1823
- Split web-pack environment
- Split web-pack environment
- No
- No
> [Issue-1823] Dev only - split webpack environment between page.js and extension.json

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-1839] Update chainlist (w34)

- .github/workflows/push-webapp.yml
- .gitignore
- packages/extension-koni-ui/src/constants/buy/banxa.ts
- #1869
- Fix buy token
- Fix buy token
- No
- No
> [Issue-1869] WebApp - Do not buy token buy Transak

- packages/extension-base/src/koni/background/handlers/Extension.ts
- #1882
- Fix bug when start with alway required option (auto lock)
- Fix bug when start with alway required option (auto lock)
- No
- No
> [Issue-1882] Handle bug related to web runner 1.1.10

- .gitignore
- packages/extension-koni-ui/src/Popup/Account/AttachReadOnly.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Stake.tsx
- packages/extension-koni-ui/src/constants/ledger.ts
- #1814
- [Ledger] Add Astar network
- [Ledger] Add Astar network
- No
- No
> [Issue-1814] [Ledger] Add support for Astar dApp Staking

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/chain-service/health-check/addressPrefix.spec.ts
- packages/extension-koni-ui/package.json
- yarn.lock
- #1861
- #1866
- #1891
- No
- No
> [Issue-1861] Update chain-list (w35-36)

- packages/extension-koni-ui/src/Popup/Confirmations/index.tsx
- #1874
- Handle the case of signing transactions from dApp using a Ledger account
- Handle the case of signing transactions from dApp using a Ledger account
- No
- No
> [Issue-1874] Handle the case of signing transactions from dApp using a Ledger account

- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- #1901
- Fix wrong message
- Fix wrong message
- No
- No
> [Issue-1901] Incorrect message when the minimum active stake is a real number

- packages/extension-koni-ui/src/Popup/Confirmations/variants/AuthorizeConfirmation.tsx
- #1912
- [AuthScreen] Fix create wrong types with create one action
- [AuthScreen] Fix create wrong types with create one action
- No
- No
> [Issue-1912] Create incorrect account when connect dApp

- packages/extension-base/src/koni/api/dotsama/crowdloan.ts
> [Issue-1860] Re-check status of the crowdloans item

- packages/extension-koni/src/content.ts
> [Issue-1906] Add injectedWeb3['subwallet-js'] placeholder to avoid extension cannot load in the firstime

- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
- #1949
- Fix error on transfer PEN on Pendulum
- Fix error on transfer PEN on Pendulum
- No
- No
> [Issue-1949] Update transfer function for Pendulum

- packages/extension-base/src/koni/background/handlers/Extension.ts
- #1939
- Improve network and asset subscription
- Improve network and asset subscription
- No
- No
> [Issue-1939] Improve network and asset subscription

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Account/AttachReadOnly.tsx
- packages/extension-koni-ui/src/constants/ledger.ts
- yarn.lock
- #1942
- [Ledger] Add some networks
- [Ledger] Add some networks
- No
- No
> [Issue-1942] [Ledger] Support connect Ledger device for more chains

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/nft/wasm_nft/index.ts
- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
- packages/extension-base/src/koni/api/tokens/wasm/index.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/chain-service/helper/index.ts
- packages/extension-base/src/services/chain-service/helper/neuroguns_psp34_abi.json
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Settings/Tokens/TokenDetail.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/TokensSelectorModal.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenGroupBalanceItem.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenSelectionItem.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenToggleItem.tsx
- packages/extension-koni-ui/src/hooks/router/useDefaultNavigate.tsx
- packages/extension-koni-ui/src/hooks/screen/home/useAccountBalance.ts
- yarn.lock
> [Issue-1941] Update chainlist (w38-39)

- packages/extension-koni-ui/src/components/WalletConnect/Network/WCNetworkBase.tsx
- #1926
- [WalletConnect] [SessionConfirm] Fix cannot scroll network modal
- [WalletConnect] [SessionConfirm] Fix cannot scroll network modal
- No
- No
> [Issue-1926] Do not scroll list network in case connect Wallet Connect

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/messaging/index.ts
- packages/extension-koni-ui/src/stores/utils/index.ts
- #1959
- Re handle case subscribe request
- Re handle case subscribe request
- No
- No
> [Issue-1959] Handle the case lost internet connection (to implement mobile app)

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftItemDetail.tsx
- #1957
- Fix cannot open Address Book modal on Send NFT screen
- Fix cannot open Address Book modal on Send NFT screen
- No
- No
> [Issue-1957] WebApp - Can't navigate Address book screen when send NFT

- packages/extension-koni-ui/src/Popup/Account/ConnectLedger.tsx
- #1971
- Update UI
- Update UI
- No
- No
> [Issue-1971] WebApp - Update UI of the List account to connect Ledger device screen

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/hooks/wallet-connect/useSelectWalletConnectAccount.ts
- #1981
- [WalletConnect] Fix error when connect with hashkey.id
- [WalletConnect] Fix error when connect with hashkey.id
- No
- No
> [Issue-1981] Extension - Error page in case connect WalletConnect

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/nft/index.ts
- packages/extension-base/src/koni/api/nft/statemint_nft/index.ts
- packages/extension-base/src/koni/api/nft/transfer.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Transaction/helper/nftParamsHandler.ts
- yarn.lock
> [issue-1982] Update chain list (w40)

- packages/extension-base/src/services/keyring-service/index.ts
- #1988
- [Inject] Switch to special account when have only one account
- [Inject] Switch to special account when have only one account
- No
- No
> [Issue-1988] Extension - Need to switch to the account in case connect to extension with only 1 account

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/hooks/wallet-connect/useSelectWalletConnectAccount.ts
- #1981
- [WalletConnect] Fix error when connect with hashkey.id
- [WalletConnect] Fix error when connect with hashkey.id
- No
- No
> [Issue-1981] WebApp - Error page in case connect WalletConnect

- packages/extension-base/src/services/keyring-service/index.ts
- #1988
- [Inject] Switch to special account when have only one account
- [Inject] Switch to special account when have only one account
- No
- No
> [Issue-1988] WebApp - Need to switch to the account in case connect to extension with only 1 account

- packages/extension-base/src/utils/index.ts
- packages/extension-koni-ui/src/contexts/InjectContext.tsx
- #1994
- [Inject] Fix logic inject wallet
- [Inject] Fix logic inject wallet
- No
- No
> [Issue-1994] WebApp - Bug when connect extension

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/migration-service/scripts/MigrateLedgerAccount.ts
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningManagement.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/parts/Overview.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Yield/YieldWithdrawPosition.tsx
- packages/extension-koni-ui/src/components/Earning/HorizontalEarningItem.tsx
- packages/extension-koni-ui/src/components/Modal/Earning/EarningMoreActionModal.tsx
- packages/extension-koni-ui/src/components/Modal/Earning/YieldPositionDetailModal.tsx
- packages/extension-koni-ui/src/components/Modal/Earning/YieldStakingDetailModal.tsx
- packages/extension-koni-ui/src/contexts/WalletModalContext.tsx
- packages/extension-koni-ui/src/hooks/screen/earning/useGroupYieldPosition.ts
- packages/extension-koni-ui/src/stores/feature/YieldPoolInfo.ts
- packages/extension-koni-ui/src/stores/utils/index.ts
- packages/extension-koni-ui/src/utils/form/validators/index.ts
- #1929
- Update UI/UX
- Update UI/UX
- No
- No
> [Issue-1929] [Yield aggregator] Update UI/UX #1929

- .github/workflows/push-master.yml
- #2017
-  Update coinbase ID on master flow
-  Update coinbase ID on master flow
- No
- No
> [Issue-2017] Update coinbase ID for product environment

- packages/extension-koni-ui/src/constants/buy/token.ts
- #2026
- Update buy token list
- Update buy token list
- No
- No
> [Issue-2026] Update buy token list

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/api/dotsama/crowdloan.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/koni/background/subscription.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-2035] Update crowdloan data

- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CheckCrowdloanContributions.tsx
- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CrowdloanContributionsResult.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningDemo.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningManagement.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningOverview.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/parts/Overview.tsx
- packages/extension-koni-ui/src/Popup/Transaction/Transaction.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Yield/Earn.tsx
- packages/extension-koni-ui/src/components/Earning/EarningItem.tsx
- packages/extension-koni-ui/src/components/Earning/HorizontalEarningItem.tsx
- packages/extension-koni-ui/src/components/Modal/BaseModal.tsx
- packages/extension-koni-ui/src/components/Modal/BaseSelectModal.tsx
- packages/extension-koni-ui/src/components/Modal/Earning/EarningInfoModal.tsx
- packages/extension-koni-ui/src/components/Modal/Earning/EarningMoreActionModal.tsx
- packages/extension-koni-ui/src/types/crowdloan.ts
> [Issue-2014] Update responsive

- packages/extension-base/package.json
- packages/extension-base/src/koni/api/nft/config.ts
- yarn.lock
- #1995
- Update IPFS link for Firefox
- Update IPFS link for Firefox
- No
- No
> [Issue-1995] Bug IPFS in Firefox browser

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Keyring/ApplyMasterPassword/index.tsx
- packages/extension-koni-ui/src/Popup/Keyring/CreatePassword.tsx
- packages/extension-koni-ui/src/Popup/Root.tsx
- #2040
- Fix error with create new password
- Fix error with create new password
- No
- No
> [Issue-2040] [Extension] WebApp - Recheck bug show apply master password screen when using webapp

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Keyring/ApplyMasterPassword/index.tsx
- packages/extension-koni-ui/src/Popup/Keyring/CreatePassword.tsx
- packages/extension-koni-ui/src/Popup/Root.tsx
- #2040
- Fix error with create new password
- Fix error with create new password
- No
- No
> [Issue-2040] [WebApp] WebApp - Recheck bug show apply master password screen when using webapp

- packages/extension-koni-ui/src/Popup/Confirmations/variants/AuthorizeConfirmation.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/ConnectWalletConnectConfirmation.tsx
- packages/extension-koni-ui/src/components/WalletConnect/Account/WCAccountSelect.tsx
- #2039
- [Confirmation] [Auth] Update text
- [Confirmation] [Auth] Update text
- No
- No
> [Issue-2039] [WebApp] Update message on the Create one account

- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CheckCrowdloanContributions.tsx
- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CrowdloanContributionsResult.tsx
- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningManagement.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/parts/Overview.tsx
- packages/extension-koni-ui/src/Popup/MissionPool/MissionItem.tsx
- packages/extension-koni-ui/src/Popup/MissionPool/index.tsx
- packages/extension-koni-ui/src/Popup/Settings/index.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/components/Earning/EarningItem.tsx
- packages/extension-koni-ui/src/components/Earning/HorizontalEarningItem.tsx
- packages/extension-koni-ui/src/components/EmptyList/EmptyList.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SideMenu/SideMenu.tsx
> Update UI responsive

- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CrowdloanContributionsResult.tsx
- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/components/Crowdloan/CrowdloanItem.tsx
- packages/extension-koni-ui/src/components/CrowdloanTable.tsx
- packages/extension-koni-ui/src/components/Earning/EarningItem.tsx
- packages/extension-koni-ui/src/components/Earning/HorizontalEarningItem.tsx
- packages/extension-koni-ui/src/constants/earning.ts
- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
- packages/extension-koni-ui/src/hooks/screen/crowdloan/useGetCrowdloanList.ts
- packages/extension-koni-ui/src/types/crowdloan.ts
- packages/extension-koni-ui/src/utils/crowdloan/index.ts
- PR for #2041 
- PR for #2018
- Fix issue related to display networks on token balance list screen: https://github.com/Koniverse/SubWallet-Extension/issues/2053
> Solve some issues

- packages/extension-base/src/services/keyring-service/index.ts
- #2056
- Increase timeout time
- Increase timeout time
- No
- No
> [Issue-2056] WebApp - Show create master password screen when reset wallet

- packages/extension-koni-ui/src/Popup/Root.tsx
- #2051
- Update auto navigate
- Update auto navigate
- No
- No
> [Issue-2051] [WebApp] Handles the case of accessing specific features via URL

- packages/extension-koni-ui/src/Popup/Root.tsx
- #2051
- Update auto navigate
- Update auto navigate
- No
- No
> [Issue-2051] Handles the case of accessing specific features via URL

- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
> [Issue 2079] fix bug calculating max transferable

- packages/extension-koni-ui/src/hooks/screen/home/useReceiveQR.ts
- #2075
- Filter list account when receive
- Filter list account when receive
- No
- No
> [Issue-2075] [Extension] Obtaining Ledger account addresses on incompatible networks is not allowed 

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CrowdloanContributionsResult.tsx
- packages/extension-koni-ui/src/Popup/DApps/DAppItem.tsx
- packages/extension-koni-ui/src/Popup/DApps/FeatureDAppItem.tsx
- packages/extension-koni-ui/src/Popup/DApps/index.tsx
- packages/extension-koni-ui/src/Popup/Settings/index.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/components/Layout/base/Base.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SideMenu/SideMenu.tsx
- packages/webapp/public/assets/reset.css
- yarn.lock
- Update responsive for dapps
- Update auto play, loop for feature dapps
- Update header height for Setting page on small screen
> [Issue - 2014] Update responsive for dapps

- packages/extension-koni-ui/src/hooks/screen/home/useReceiveQR.ts
- #2075
- Filter list account when receive
- Filter list account when receive
- No
- No
> [Issue-2075] [WebApp] Obtaining Ledger account addresses on incompatible networks is not allowed

- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
> Update issue 2079 for web app

- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Transaction/parts/FreeBalance.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Yield/Earn.tsx
- #2089
- Fix not subscribe balance after xcm
- Fix not subscribe balance after xcm
- No
- No
> [Issue-2089] Do not subcribe balance after XCM

- packages/extension-base/src/services/chain-service/handler/EvmChainHandler.ts
- packages/extension-koni-ui/src/Popup/BuyTokens.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/AddTokenConfirmation.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
- packages/extension-koni-ui/src/Popup/Settings/Tokens/FungibleTokenImport.tsx
- packages/extension-koni-ui/src/Popup/Settings/Tokens/TokenDetail.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/CancelUnstake.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/ClaimReward.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Withdraw.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/components/Field/TokenTypeSelector.tsx
- packages/extension-koni-ui/src/components/Modal/GlobalSearchTokenModal.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/TokensSelectorModal.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenBalanceSelectionItem.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenSelectionItem.tsx
- packages/extension-koni-ui/src/utils/form/form.ts
- #1946
- Show `Token Name` for some screen and modal
- Show `Token Name` for some screen and modal
- No
- No
> [Issue-1946] Add "Token Name" to the Token Details and Import Token screen

- packages/extension-koni-ui/src/Popup/CrowdloanUnlockCampaign/CrowdloanContributionsResult.tsx
- packages/extension-koni-ui/src/components/Crowdloan/CrowdloanItem.tsx
- packages/extension-koni-ui/src/components/CrowdloanTable.tsx
> [Issue - 2080] Show the unlocked crowdloan contribution

- packages/extension-koni-ui/src/Popup/MissionPool/MissionDetailModal.tsx
Update network display for mission detail
> [Mission Pool] Update network display for mission detail

- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/storage-service/db-stores/NftCollection.ts
- #1978
- Fix not show NFT after import
- Fix not show NFT after import
- No
- No
> [Issue-1978] [Extension] WebApp - NFT isn't displayed after import successfully

- packages/extension-base/src/koni/api/xcm/xTokens.ts
- #2091
- Fix XCM from Parallel
- Fix XCM from Parallel
- No
- No
> [Issue-2091] An error occurred when transferring XCM USDT (Parallel --> Statemint)

- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/storage-service/db-stores/NftCollection.ts
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftCollections.tsx
- packages/extension-koni-ui/src/constants/modal.ts
- #1978
- Fix not show NFT after import
- Fix not show NFT after import
- No
- No
> [Issue-1978] WebApp - NFT isn't displayed after import successfully

- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailUpperBlock.tsx
> [Issue-2104] Fix UI bug on token detail screen

- packages/extension-koni-ui/src/Popup/EarningDone/Content/index.tsx
- #2103
- Update UI/UX
- Update UI/UX
- No
- No
> [Issue-2103] Bugs related to connect mobile wallet

- packages/extension-base/src/koni/api/staking/bonding/astar.ts
- #2129
- Fix error when unstaking astar
- Fix error when unstaking astar
- No
- No
> [Issue-2129] Bug decoding dApp staking

- packages/webapp/public/assets/reset.css
> [Issue-2141] Update UX

- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- #2152
- Support nomination pool for Vara network
- Support nomination pool for Vara network
- No
- No
> [Issue-2152] Support nomination pool for Vara network

- packages/extension-koni-ui/src/Popup/Settings/Tokens/ManageTokens.tsx
- packages/extension-koni-ui/src/components/Field/TokenSelector.tsx
- packages/extension-koni-ui/src/components/Modal/GlobalSearchTokenModal.tsx
- packages/extension-koni-ui/src/hooks/assets/index.ts
- packages/extension-koni-ui/src/hooks/assets/useChainAssets.ts
- packages/extension-koni-ui/src/hooks/screen/home/useReceiveQR.ts
> [Issue-2158] Filter assets of removed chains

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Confirmations/variants/ConnectWalletConnectConfirmation.tsx
- packages/extension-koni-ui/src/contexts/WalletModalContext.tsx
- packages/extension-koni-ui/src/hooks/wallet-connect/useSelectWalletConnectAccount.ts
- #2119
- [WalletConnect] Handle case session have no namespace
- [WalletConnect] Handle case session have no namespace
- No
- No
> [Issue-2119] Update Wallet Connect namespace

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/dotsama/balance.ts
- packages/extension-koni-ui/package.json
- yarn.lock
- #2154
- Fix error when transfer ENJ
- Fix error when transfer ENJ
- No
- No
> [Issue-2154] [Extension] Can not get balance of the ENJ token

- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
- #2162
- Update max nomination
- Update max nomination
- No
- No
> [Issue-2162] Re-check chainStakingMetadata

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/dotsama/balance.ts
- packages/extension-koni-ui/package.json
- yarn.lock
- #2154
- Fix error when transfer ENJ
- Fix error when transfer ENJ
- No
- No
> [Issue-2154] [WebApp] Can not get balance of the ENJ token

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/chain-service/handler/SubstrateApi.ts
- packages/extension-base/src/services/chain-service/handler/chain-spec/goldberg.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-2178] Update chainlist (w46)

- packages/extension-koni-ui/src/constants/earning.ts
> [Issue-2192] Hide exclusive rewards tag in earning page

- packages/extension-base/src/koni/api/xcm/index.ts
- packages/extension-base/src/koni/api/xcm/polkadotXcm.ts
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/services/chain-service/health-check/provider.spec.ts
- packages/extension-base/src/services/transaction-service/xcm.spec.ts
- #2196
- Fix XCM on Astar
- Update XCM function on Astar
- No
- No
> [Issue-2196] Update XCM for Astar

- packages/extension-base/src/koni/api/staking/bonding/astar.ts
- #2139
- [Astar] Fix not mark staked on select modal
- [Astar] Fix not mark staked on select modal
- No
- No
> [Issue-2139] Bug decode dApp address

- packages/extension-koni-ui/src/Popup/Root.tsx
- #2207
- Decrease required data to display UI
- Decrease required data to display UI
- No
- No
> [Issue-2207] Browser waste time when load extension

- packages/extension-koni-ui/src/Popup/DApps/DAppItem.tsx
Fix issues mentioned in this image
> [Issue 1977] handle description height of Dapp item

- packages/extension-base/src/koni/api/dotsama/crowdloan.ts
- packages/extension-base/src/koni/background/subscription.ts
- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/components/Crowdloan/CrowdloanItem.tsx
- packages/extension-koni-ui/src/components/Crowdloan/index.tsx
- packages/extension-koni-ui/src/components/index.ts
- packages/extension-koni-ui/src/hooks/screen/crowdloan/useGetCrowdloanList.ts
- packages/extension-koni-ui/src/types/crowdloan.ts
- packages/extension-koni-ui/src/utils/crowdloan/index.ts
- packages/extension-koni-ui/src/utils/index.ts
> [Issue-2199] Update new way to fetch crowdloan

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/history-service/index.ts
- packages/extension-base/src/services/subscan-service/index.ts
- packages/extension-base/src/utils/index.ts
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- Optimize way to show history
> [Issue-2223] Optimize way to show history

- packages/extension-koni-ui/src/Popup/Home/Tokens/index.tsx
- packages/extension-koni-ui/src/Popup/Root.tsx
- packages/extension-koni-ui/src/components/Layout/PageWrapper.tsx
- packages/extension-koni/public/index.html
> [Issue-2228] Add the loading effect when open app in case loading data

- packages/extension-koni-ui/src/Popup/Account/AttachReadOnly.tsx
- packages/extension-koni-ui/src/constants/ledger.ts
- #2219
- Unblock actions for Aleph Zero network ledger
- Unblock actions for Aleph Zero network ledger
- No
- No
> [Issue-2219] Support staking AZERO with Ledger

- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
> [Issue 2246] filter out inactive pools

- packages/extension-koni-ui/src/components/Layout/parts/SideMenu/index.tsx
- packages/webapp/public/assets/reset.css
> [Issue-2015] Fix UI issue related to Safari

- packages/extension-base/src/koni/api/staking/bonding/index.ts
- packages/extension-base/src/koni/background/cron.ts
- packages/extension-base/src/koni/background/subscription.ts
- #2213
- Temporarily do not use `totalReward`
- Remove cron to subscribe `totalReward` data
- No
- No
> [Issue-2213] Bug showing staking rewards on Moonbeam

- packages/extension-koni-ui/src/components/Layout/parts/Header/Balance.tsx
Handling ui small screen by adding media queries for each screen width
> [Issue 2210] Fix Ui bug on small screen

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-2287] Update chain-list (w48)

- packages/extension-koni-ui/src/Popup/Transaction/helper/staking/stakingHandler.ts
> [Issue 2304] Update showing estimated withdrawal time

- packages/extension-base/src/services/chain-service/constants.ts
- #2301
- Update metadata staking for Vara
- Update metadata staking for Vara
- No
- No
> [Issue-2301] Update APY for VARA staking

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- yarn.lock
> [Issue-2302] Update chain-list (w49)

- packages/extension-koni-ui/src/Popup/BuyTokens.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/parts/Qr/DisplayPayload/DisplayPayloadModal.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftItemDetail.tsx
- packages/extension-koni-ui/src/Popup/Keyring/CreatePassword.tsx
- packages/extension-koni-ui/src/components/Layout/parts/ConnectWebsiteModal.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/index.tsx
- packages/extension-koni-ui/src/components/Modal/AccountSelectorModal.tsx
- packages/extension-koni-ui/src/components/Modal/AddressBook/AddressBookModal.tsx
- packages/extension-koni-ui/src/components/Modal/BaseModal.tsx
- packages/extension-koni-ui/src/components/Modal/BaseSelectModal.tsx
- packages/extension-koni-ui/src/components/Modal/Campaign/CampaignBannerModal.tsx
- packages/extension-koni-ui/src/components/Modal/Customize/CustomizeModal.tsx
- packages/extension-koni-ui/src/components/Modal/GlobalSearchTokenModal.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/ReceiveQrModal.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/TokensSelectorModal.tsx
- packages/extension-koni-ui/src/components/Modal/RequestCameraAccessModal.tsx
- packages/extension-koni-ui/src/components/Modal/RequestCreatePasswordModal.tsx
- packages/extension-koni-ui/src/components/Modal/ResetWalletModal.tsx
- packages/extension-koni-ui/src/components/Modal/UnlockModal.tsx
- packages/extension-koni-ui/src/components/Modal/Wallet/DisconnectExtensionModal.tsx
- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
- packages/extension-koni-ui/src/hooks/modal/useConfirmModal.ts
1. List of modified components 
- Wrapped in BaseModal
+ Center position
1. Delete chain
2. Token detail
3. Disconnect wallet
4. Delete address book
5. Delete token 
6. Delete Account
7. Forgot password
8. Buy Tokens Disclaimer
9. Display Payload Modal
10. Connect Website Modal
11. Campaign Banner Modal
12. Receive Qr Modal
13. Request Camera Access Modal
14. Request Create Password Modal
15. Disconnect Wallet
16. Disconnect Extension Modal
17. Reset Wallet Modal
18. Unlock Modal
> [Issue 2209] WebApp - Continue Fix modal height in mobile

- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- PR for #2326 
- Fix issue related to history filter on Web App
> [Issue-2326] Webapp: fix issue related to history filter

- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
> [Issue-2326] Fix issue related to history filter

- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
UI bug on the Buy token screen on the Firefox browser
> [Issue-1849] UI bug on the Buy token screen on the Firefox browser

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-base/src/services/migration-service/scripts/tokens/MigratePolygonUSDCProvider.ts
- packages/extension-base/src/services/migration-service/scripts/tokens/MigrateToken.ts
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-2329] Update chain-list (w50)

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Home/Staking/StakingDetailModal.tsx
- yarn.lock
- #2353
- Add more XCM channels
- Add more XCM channels
- No
- No
> [Issue-2353] Support some XCM transfers

- packages/extension-base/src/constants/staking.ts
- packages/extension-base/src/koni/api/staking/bonding/relayChain.ts
- #2324
- Update logic to get staking status
- Update logic to get staking status
- No
- No
> [Issue-2324] Update top nominators getting rewards

- packages/extension-base/src/koni/api/staking/bonding/astar.ts
- #2370
- Update ASTAR api staking endpoint
- Update ASTAR api staking endpoint
- No
- No
> [Issue-2370] Update API staking for Astar

- packages/extension-koni-ui/src/Popup/Home/Inscriptions/InscriptionItemDetail.tsx
- packages/extension-koni-ui/src/Popup/Home/Inscriptions/InscriptionItemList.tsx
- packages/extension-koni-ui/src/Popup/Home/Inscriptions/components/InscriptionGalleryWrapper.tsx
- packages/extension-koni-ui/src/Popup/Home/Inscriptions/components/InscriptionImage.tsx
- packages/extension-koni-ui/src/Popup/Home/Inscriptions/types.ts
- packages/extension-koni-ui/src/Popup/Home/PortfolioPage/index.tsx
- packages/extension-koni-ui/src/Popup/router.tsx
- packages/extension-koni-ui/src/components/NoContent.tsx
- packages/extension-koni-ui/src/contexts/WebUIContext.tsx
- #2380
- Update UI
- Update UI
- No
- No
> [Issue-2380] Showing ordinals on webapp

- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/index.tsx
Sort the Current account on top in the Account selector
> [Issue-2318] Sort the Current account on top in the Account selector

- packages/extension-base/src/services/transaction-service/index.ts
- packages/extension-koni-ui/src/Popup/Home/History/Detail/parts/Layout.tsx
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- packages/extension-koni-ui/src/Popup/TransactionDone.tsx
- packages/extension-koni-ui/src/components/History/HistoryItem.tsx
- packages/extension-koni-ui/src/utils/history/index.ts
- packages/extension-koni-ui/src/utils/index.ts
- PR for #2362 
- PR for #2373
> [Issue-2362][Issue-2373] Fix issue related to history

- packages/extension-base/src/koni/api/nft/ordinal_nft/index.ts
- packages/extension-base/src/services/chain-service/utils.ts
> [Issue 2399] Add more inscriptions

- packages/extension-base/src/koni/api/yield/index.ts
> [Issue 2400] fix bug rounding xcm fee

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-2404] Update chain-list (w52)

- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/koni/background/subscription.ts
- packages/extension-koni-ui/src/Popup/Home/Tokens/UpperBlock.tsx
> [Issue-2381] Update reload balance UI

- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailModal.tsx
- packages/extension-koni/public/locales/en/translation.json
- packages/extension-koni/public/locales/ja/translation.json
- packages/extension-koni/public/locales/ru/translation.json
- packages/extension-koni/public/locales/vi/translation.json
- packages/extension-koni/public/locales/zh/translation.json
- packages/web-runner/public/locales/en/translation.json
- packages/web-runner/public/locales/ja/translation.json
- packages/web-runner/public/locales/ru/translation.json
- packages/web-runner/public/locales/vi/translation.json
- packages/web-runner/public/locales/zh/translation.json
> [Issue-2340] Update the Token details screen

- packages/extension-inject/src/bundle.ts
> [Issue-2413] Fix error can not connect injected wallet via WalletConnect

- packages/extension-koni-ui/src/components/TokenItem/TokenSelectionItem.tsx
Fix UI issue related to token selector
> [Issue-2203] Fix UI issue related to token selector

- packages/extension-koni-ui/src/Popup/MissionPool/MissionDetailModal.tsx
- packages/extension-koni-ui/src/Popup/MissionPool/MissionItem.tsx
- packages/extension-koni-ui/src/Popup/MissionPool/index.tsx
- packages/extension-koni-ui/src/Popup/MissionPool/predefined.ts
> [Issue-2395] Disable out date mission pool from clickable

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- yarn.lock
> [Issue-2425] Update chain-list (w52) (2)

- packages/extension-koni-ui/src/Popup/Account/NewSeedPhrase.tsx
- packages/extension-koni-ui/src/Popup/Keyring/ChangePassword.tsx
- packages/extension-koni-ui/src/Popup/Keyring/CreatePassword.tsx
- packages/extension-koni-ui/src/components/BackgroundExpandView.tsx
- packages/extension-koni-ui/src/components/InstructionContainer.tsx
- packages/extension-koni-ui/src/components/Modal/Account/AccountTypeModal.tsx
- packages/extension-koni-ui/src/components/Modal/BaseModal.tsx
- packages/extension-koni-ui/src/components/Modal/TermsAndConditions/GeneralTermModal.tsx
- packages/extension-koni-ui/src/components/Modal/TermsAndConditions/SeedPhraseTermModal.tsx
- packages/extension-koni-ui/src/components/WordPhrase.tsx
**Describe the task**
Add T&C for webapp
Link doc: https://www.notion.so/subwallet/SubWallet-Th-m-T-C-cho-ng-d-ng-243dabfe04f74347bfc400277655485d?pvs=4
Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=14558-131362&mode=design&t=olAR2RwF7QyBN7Yj-4
> [Issue 2427] WebApp - Add T&C for webapp

- packages/extension-base/src/constants/index.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/utils/eth.ts
- #2412
- [Hotfix] Multiple gas fee for EVM transaction
- [Hotfix] Multiple gas fee for EVM transaction
- No
- No
> [Issue-2412] Hot fix estimating EVM transaction fee

- packages/extension-koni-ui/src/constants/transaction.ts
> [Issue-2438] Extension - Handle the case of default untick checkbox Bond reward when Claim reward

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-koni-ui/package.json
- yarn.lock
#2447 
- Update new logic for earning
- Temporarily blocking ARCH token transfer.
- Check VARCH balances, cDOT-7/14 balances.
- Check parallel provider (Dwellir).
- No
- No
> [Issue-2447] Update chainlist

- packages/extension-koni-ui/src/hooks/screen/staking/useGetSupportedStakingTokens.ts
> [Issue-2452] Show custom network on the token list when nominate

- packages/extension-koni-ui/src/Popup/Root.tsx
> [Issue-2390] Fix problems require account on detect phishing page

- packages/extension-koni-ui/src/Popup/Home/Tokens/Banner.tsx
- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailList.tsx
- packages/extension-koni-ui/src/constants/banner.ts
- packages/extension-koni-ui/src/constants/index.ts
> [Issue-2482] WebApp - Add banner for token list page

- packages/extension-koni-ui/src/Popup/Settings/index.tsx
- packages/extension-koni-ui/src/constants/common.ts
> [Issue-2467] Support "Request a feature" feature

- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftCollectionDetail.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftCollections.tsx
- packages/extension-koni-ui/src/Popup/Home/Staking/index.tsx
> [Issue-2487] Fix issue related to crowdloan banner

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/staking/bonding/index.ts
- packages/extension-base/src/koni/api/staking/bonding/paraChain.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/package.json
- yarn.lock
#2489 
Update chainlist
- Add Manta Atlantic network and support in-app staking.
- Add BNCS, support subcribe balance and transfer token
- Jur network RPC
- No
- No
> [Issue-2489] Update chainlist

- packages/extension-koni-ui/src/Popup/DApps/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/parts/Overview.tsx
- packages/extension-koni-ui/src/Popup/Home/Tokens/index.tsx
> [Issue-2417] Webapp - Fix some UI bug (Round 2)

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-base/src/services/storage-service/db-stores/YieldPositionStore.ts
- packages/extension-koni-ui/src/Popup/Transaction/helper/staking/base.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/Yield/YieldUnstake.tsx
- #2067
- Update logic withdraw pool
- Update logic withdraw pool
- No
- No
> [Issue-2067] Update logic withdraw pool

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/services/event-service/types.ts
- packages/extension-base/src/services/history-service/index.ts
- packages/extension-base/src/services/transaction-service/index.ts
- packages/extension-base/src/services/transaction-service/types.ts
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- packages/extension-koni-ui/src/constants/history.ts
**Describe the task**
Update history status of the local history in case timeout
**Actual:** The history show status = Failed if timeout (2 minutes)
**Expect:** Sync status with Subscan to show correct status
> [issue 2387] Update history status of the local history in case timeout

- packages/extension-base/src/koni/background/handlers/Tabs.ts
- packages/extension-base/src/utils/fetchEvmChainInfo.ts
- packages/extension-base/src/utils/index.ts
> [Issue-2472] Support import EVM chain-list online with switch method

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/services/campaign-service/index.ts
- packages/extension-base/src/services/storage-service/DatabaseService.ts
- packages/extension-base/src/services/storage-service/db-stores/Campaign.ts
- #2038
- Handle case update and remove campaign
- Handle case update and remove campaign
- No
- No
> [Issue-2038] Improve notification/banner in app feature

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/staking/bonding/amplitude.ts
- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-base/src/koni/api/staking/paraChain.ts
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/package.json
- yarn.lock
#2492 
- Support in-app staking for KREST
- Add new RPC: wss://krest.unitedbloc.com/
- Support in-app staking for KREST
- Add new RPC: wss://krest.unitedbloc.com/
- No
- No
> [Issue-2492] Support in-app staking for KREST

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/xcm/xTokens.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-koni-ui/package.json
- yarn.lock
#2508 
- Add token
- Update token priceId
- Update XCM paths
- Update RPC
- Support XCM transfer between Manta Atlantic and other networks: https://github.com/Koniverse/SubWallet-ChainList/issues/177
- Update Jur default RPC
- Update Manta priceId
- No
- No
> [Issue-2508] Update chainlist

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/earning-service/handlers/lending/interlay.ts
- packages/extension-base/src/services/earning-service/handlers/liquid-staking/acala.ts
- packages/extension-base/src/services/earning-service/handlers/liquid-staking/bifrost.ts
- packages/extension-base/src/services/earning-service/handlers/liquid-staking/parallel.ts
- packages/extension-base/src/services/earning-service/handlers/liquid-staking/stella-swap.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/base.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/relay-chain.ts
- packages/extension-base/src/services/earning-service/handlers/nomination-pool/index.ts
- packages/extension-base/src/services/earning-service/handlers/special.ts
- packages/extension-base/src/types/yield/actions/join/submit.ts
- packages/web-runner/webpack.config.cjs
- https://github.com/Koniverse/SubWallet-Mobile/issues/1393
- https://github.com/Koniverse/SubWallet-Extension/issues/2514
- Fix wrong earning status for CTC
- Fix cannot use native stake for Moonbeam
- Fix wrong earning status for CTC
- Fix cannot use native stake for Moonbeam
- No
- No
>  [Earning] Update logic to fix some bug

- packages/extension-koni-ui/src/hooks/screen/home/useGetChainSlugsByAccountType.ts
> [Issue-2518] Fix issue related to detect account type

- packages/extension-base/src/koni/api/yield/bifrost-liquid-staking.ts
- packages/extension-base/src/koni/api/yield/index.ts
- #2537
- Fix earn more action for bifrost staking
- Fix earn more action for bifrost staking
- No
- No
> [Issue-2537] [WebApp] Error when perform liquid staking with Bifrost Polkadot

- packages/extension-base/src/services/earning-service/handlers/liquid-staking/bifrost.ts
- #2537
- Fix earn more action for Bifrost staking
- Fix earn more action for Bifrost staking
- No
- No
> [Issue-2537] Error when perform liquid staking with Bifrost Polkadot 

- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
- #2540
- Update logic fetching balance with Genshiro network
- Update logic fetching balance with Genshiro network
- No
- No
> [Issue-2540] Fix bug not showing GENS token from Genshiro

- packages/extension-base/src/koni/api/staking/bonding/amplitude.ts
- packages/extension-base/src/koni/api/staking/paraChain.ts
- #2544
- Fix case delegator does not exist
- Fix case delegator does not exist
- No
- No
> [Issue-2544] Block choosing collator in case stake more for Krest

- packages/extension-koni-ui/src/Popup/Home/Staking/MoreActionModal.tsx
> [Issue-2497] Extension - Change "Claim rewards" to "Check rewards" for dApp staking

- packages/extension-base/src/services/transaction-service/constants.ts
- packages/extension-base/src/utils/eth.ts
- #2336
- Update fee for BSC
- Update timeout threshold
- Update fee for BSC
- Update timeout threshold
- No
- No
> [Issue-2336] Check fee estimation on EVM networks

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/utils/index.ts
- yarn.lock
> [Issue-2586] Update chainlist

- packages/extension-koni-ui/src/Popup/Transaction/variants/Earn.tsx
- Update account filter for earn transaction
> Update account filter for earn transaction

- packages/extension-base/src/page/SubWalleEvmProvider.ts
- packages/extension-inject/src/bundle.ts
- packages/extension-koni/src/content.ts
> [Issue-2588] Fix bug can't start uniswap with SubWallet 

- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningOptions/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningPositions/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningPools/index.tsx
- packages/extension-koni-ui/src/Popup/Home/index.tsx
- packages/extension-koni-ui/src/components/Modal/Announcement/ClaimDappStakingRewardsModal.tsx
- packages/extension-koni-ui/src/components/Modal/Announcement/EarningMigrationModal.tsx
- packages/extension-koni-ui/src/components/Modal/Announcement/index.ts
- packages/extension-koni-ui/src/components/Modal/Earning/index.ts
- packages/extension-koni-ui/src/components/Modal/index.tsx
- packages/extension-koni-ui/src/constants/localStorage.ts
- packages/extension-koni-ui/src/constants/modal.ts
- packages/extension-koni-ui/src/contexts/WalletModalContext.tsx
Update UI for earning screens
Update earning migration announcement #2599
> [Issue-2598][Issue-2599] Update UI for earning screens, update earning migration announcement

- packages/extension-koni-ui/src/Popup/Welcome.tsx
- packages/extension-koni-ui/src/components/Account/Info/AccountBriefInfo.tsx
- packages/extension-koni-ui/src/components/MetaInfo/parts/ChainItem.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenBalanceSelectionItem.tsx
- packages/extension-koni-ui/src/components/TokenItem/TokenSelectionItem.tsx
- packages/extension-koni-ui/src/components/WordPhrase.tsx
> [Issue-2449] Extension - Fix some UI bug

- packages/extension-base/src/koni/api/tokens/evm/transfer.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/transaction-service/index.ts
- packages/extension-base/src/utils/eth.ts
- #2606
- Fix gas fee for Web Energy Chain
- Remove override gas fee for transaction from dApp
- Max priority fee must always be greater than `1 (10^-9 GWEI)`
- No
- No
> [Issue-2606] Extension - Update estimating EVM transaction fee for Energy Web X

- packages/extension-base/src/services/earning-service/service.ts
> [Issue-2612] Update earning positions fetching logic related to network state

- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningOptions/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningPositions/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningPools/index.tsx
- packages/extension-koni-ui/src/components/Layout/base/Base.tsx
> [Issue-2631]Extension - Update tabbar

- packages/extension-web-ui/src/Popup/Home/Tokens/Banner.tsx
- packages/extension-web-ui/src/Popup/Home/Tokens/DetailList.tsx
> [Issue-2509] Fix issue related to showing the banner in mobile mode of webapp

- packages/extension-base/src/services/chain-service/index.ts
#2664 
- Enable priceId update online
- Enable priceId update online
- No
- No
> [Issue-2664] Enable priceId update online

- packages/extension-base/src/koni/api/tokens/evm/transfer.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/earning-service/handlers/liquid-staking/stella-swap.ts
- packages/extension-base/src/services/fee-service/service.ts
- packages/extension-base/src/services/fee-service/utils/index.ts
- packages/extension-base/src/services/transaction-service/index.ts
- packages/extension-base/src/types/fee/index.ts
- packages/extension-base/src/types/index.ts
- packages/extension-base/src/utils/eth.ts
- packages/extension-base/src/utils/index.ts
- packages/extension-koni/webpack.shared.cjs
- packages/web-runner/webpack.config.cjs
- packages/webapp/webpack.config.cjs
- #2670
- Hotfix fee for BSC
- Build middleware for EVM fee service
- Hotfix fee for BSC
- Build middleware for EVM fee service
- No
- No
> [Issue-2670] [Extension] Improve EVM network fee

- packages/extension-base/src/utils/reportError.ts
- packages/extension-koni-ui/src/Popup/ErrorFallback.tsx
> [Issue-2649] Add send crash log feature

- packages/extension-base/src/services/earning-service/service.ts
> [Issue-2682] Reload earning after transaction is done

- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/services/chain-service/constants.ts
- #2688
- Hotfix disable transfer for NUUM token
- Hotfix disable transfer for NUUM token
- No
- No
> [Issue-2688] Hotfix temporary disable transfer for NUUM token

- packages/extension-web-ui/src/Popup/Transaction/variants/Earn.tsx
- packages/extension-web-ui/src/components/Field/Earning/EarningValidatorSelector.tsx
- packages/extension-web-ui/src/components/SelectValidatorInput.tsx
- packages/extension-web-ui/src/hooks/modal/useSelectValidators.ts
> [Issue-2691] Add auto select earning validators

- packages/extension-base/src/services/chain-service/index.ts
> [Issue 2717] Update XCM ref map

- packages/extension-web-ui/src/Popup/TransactionDone.tsx
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/ja/translation.json
- packages/webapp/public/locales/ru/translation.json
- packages/webapp/public/locales/vi/translation.json
- packages/webapp/public/locales/zh/translation.json
> [Issue - 2706] WebApp - Update transaction result screen

- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-base/src/services/earning-service/constants/chains.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/relay-chain.ts
- packages/extension-base/src/types/yield/info/chain/target.ts
- packages/extension-base/src/types/yield/info/pallet.ts
- packages/extension-web-ui/src/Popup/Home/Earning/EarningEntry/index.tsx
- packages/extension-web-ui/src/Popup/Home/Earning/EarningPreview/EarningPreviewOptions.tsx
- packages/extension-web-ui/src/Popup/Home/Earning/EarningPreview/EarningPreviewOutlet.tsx
- packages/extension-web-ui/src/Popup/Transaction/variants/Earn.tsx
- packages/extension-web-ui/src/components/Earning/EarningOptionItem.tsx
- packages/extension-web-ui/src/components/Earning/desktop/EarningOptionDesktopItem.tsx
- packages/extension-web-ui/src/components/Modal/BaseModal.tsx
- packages/extension-web-ui/src/components/Modal/BaseSelectModal.tsx
- packages/extension-web-ui/src/components/Modal/Earning/EarningInstructionModal.tsx
- packages/extension-web-ui/src/hooks/common/useGetChainSlugsByCurrentAccount.ts
- packages/extension-web-ui/src/types/navigation.ts
- packages/extension-web-ui/src/utils/common/common.ts
- packages/extension-web-ui/src/utils/earning.ts
> [Issue-2626] Update earning for staking reward

- packages/extension-koni-ui/src/Popup/Settings/index.tsx
> [Issue-2729] Extension - Update Subject email in case select Contact support

- packages/extension-web-ui/src/Popup/Settings/index.tsx
> [Issue-2737] WebApp - Update Subject email in case select Contact support

- packages/extension-base/src/services/subscan-service/subscan-chain-map.ts
- #2732
- [Hotfix] Hot fix for `manta_network` and `continuum_network`
- [Hotfix] Hot fix for `manta_network` and `continuum_network`
- No
- No
> [Hotfix] [Issue-2732] Auto detect balance

- packages/extension-koni-ui/src/constants/common.ts
> [Issue-2759_extension] Extension - Update email support

- packages/extension-base/src/services/migration-service/scripts/MigrateTransactionHistoryBySymbol.ts
- packages/extension-base/src/services/migration-service/scripts/databases/MigrateAssetSetting.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- #2694
- Update migrate script
- Update migrate script
- No
- No
> [Issue-2694] Update chainlist

- packages/extension-koni-ui/src/Popup/Account/ConnectLedger.tsx
- packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
**Describe the bug**
**To reproduce the bug**
Step:
1. Perform connect a Ledger device
2. On list account, perform scroll and observe the displayed screen
Actual: Unable to scroll list account
Reason: Zoom in/Zoom out browser
https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4bf594f5-2bba-4499-9e8a-16bbeb8cffc1
> [Issue 2608] Extension - Unable to scroll list account when connect a Ledger device

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- #2767
- Update chain-list stable version
- Update chain-list stable version
- No
- No
> [Issue-2767] Update chainlist

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/earning-service/constants/chains.ts
- packages/extension-base/src/services/earning-service/service.ts
- packages/extension-base/src/services/migration-service/scripts/MigrateTransactionHistoryBySymbol.ts
- packages/extension-base/src/services/migration-service/scripts/databases/MigrateAssetSetting.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-base/src/services/transaction-service/utils.ts
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/components/Modal/ReceiveModal/ReceiveQrModal.tsx
- packages/extension-web-ui/package.json
- packages/extension-web-ui/src/components/Modal/ReceiveModal/ReceiveQrModal.tsx
- yarn.lock
- #2771 
- Update chainlist 0.2.45
- Update chainlist 0.2.45
- No
- No
> [Issue-2771] Update chainlist 0.2.45

- packages/extension-web-ui/src/Popup/Account/ConnectLedger.tsx
- packages/extension-web-ui/src/hooks/ledger/useLedger.ts
**Describe the bug**
**To reproduce the bug**
Step:
1. Perform connect a Ledger device
2. On list account, perform scroll and observe the displayed screen
Actual: Unable to scroll list account
Reason: Zoom in/Zoom out browser
https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4bf594f5-2bba-4499-9e8a-16bbeb8cffc1
> [Issue 2608] WebApp - Unable to scroll list account when connect a Ledger device

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/constants/index.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/migration-service/scripts/databases/AutoEnableSomeTokens.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
> [Issue 2786] Support XCM for PINK token

- packages/extension-web-ui/src/Popup/RedirectHandler.tsx
- packages/extension-web-ui/src/Popup/Root.tsx
- packages/extension-web-ui/src/Popup/Transaction/variants/Swap.tsx
- packages/extension-web-ui/src/Popup/router.tsx
- packages/extension-web-ui/src/constants/router.ts
> [Issue-2784] handle to add swap button to Extension

- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
- #2799
- Fix error with show frozen balance
- Fix error with show frozen balance
- No
- No
> [Issue-2799] Error parsing token balance for frozen asset on Asset Hub

- packages/extension-koni-ui/src/Popup/Settings/MissionPool/MissionDetailModal.tsx
- packages/extension-koni-ui/src/Popup/Settings/MissionPool/MissionPoolItem.tsx
> [Issue-2796] Extension - Improve UI for Mission Pools

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
> [Issue-2793] Handle case slow getting max transferable cause wrong amount when submit max transfer

- packages/extension-base/src/constants/index.ts
- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- #2798
- #2814 
- Update logic calculate max transfer xcm
- Add alert when transfer all native token
- Update logic calculate max transfer xcm
- Add alert when transfer all native token
- No
- No
> [Issue-2798] Check transfer logic that can potentially affect ED

- packages/extension-koni-ui/src/Popup/Home/Crowdloans/index.tsx
- packages/extension-koni-ui/src/Popup/Home/History/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftCollections.tsx
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
Related issue: #2791
- Please, let's check this issue on the NFTs, History, and Crowdloans tabs.
> [Issue-2791] Extension - Do not show balance in case standing on History list to search token

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-base/src/services/event-service/index.ts
- packages/extension-base/src/services/event-service/types.ts
- #2824
- Fix case data subscription incorrect
- Fix case data subscription incorrect
- No
- No
> [Issue-2824] Integrate asset online ( Round 2)

- packages/extension-web-ui/src/Popup/Transaction/variants/SendFund.tsx
> [Issue-2817] WebApp - Disable submit button when getting max transferable

- packages/extension-base/src/services/earning-service/handlers/native-staking/para-chain.ts
- #2829
- Update withdraw time for parachain
- Allow withdraw action at the beginning of the target round instead of at the end.
- No
- No
> [Issue-2829] Update withdraw time for parachain

- packages/extension-web-ui/src/Popup/Transaction/variants/SendFund.tsx
> [Issue-2818] WebApp - Add message to warn about asset loss when click Transfer Max

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/chain-service/utils/patch.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- #2851 
- Update chainlist
- Update chainlist
- No
- No
> [Issue-2851] Update chainlist

- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningOptions/index.tsx
- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningPositions/index.tsx
- packages/extension-koni/public/locales/en/translation.json
- packages/extension-koni/public/locales/ja/translation.json
- packages/extension-koni/public/locales/ru/translation.json
- packages/extension-koni/public/locales/vi/translation.json
- packages/extension-koni/public/locales/zh/translation.json
> [Issue-2847] Extension - Update message when navigate user to the Astar portal to stake

- packages/extension-koni-ui/src/Popup/Home/Earning/EarningEntry/EarningOptions/index.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/Earn.tsx
- packages/extension-koni-ui/src/components/Earning/EarningOptionItem.tsx
- packages/extension-koni-ui/src/components/Earning/EarningPositionItem.tsx
- packages/extension-koni-ui/src/components/Field/Earning/EarningPoolSelector.tsx
- packages/extension-koni-ui/src/components/NetworkTag.tsx
- packages/extension-koni-ui/src/components/index.ts
- packages/extension-koni-ui/src/types/earning.ts
> [Issue-2827] Extension - Update UI for earning feature

- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
- #2885
- Fix error when fetching balance with Enjin relay chain
- Fix error when fetching balance with Enjin relay chain
- No
- No
> [Issue-2885] Error when fetching balance with Enjin Relay Chain

- packages/extension-web-ui/src/Popup/Confirmations/variants/Transaction/variants/Swap.tsx
> [Issue-2912] Webapp-Fix issue related recipient of swap

- packages/extension-base/src/services/chain-service/constants.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/amplitude.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/para-chain.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/relay-chain.ts
- #2830
- Update withdraw time by timestamp for parachain and amplitude group
- Update withdraw time by timestamp for parachain and amplitude group
- No
- No
> Update withdraw time by timestamp

- packages/extension-base/src/background/KoniTypes.ts
- packages/extension-base/src/koni/api/nft/assethub_nft/index.ts
- packages/extension-base/src/koni/api/nft/assethub_unique/index.ts
- packages/extension-base/src/koni/api/nft/index.ts
- packages/extension-base/src/koni/api/nft/nft.ts
- packages/extension-base/src/koni/api/nft/statemine_nft/index.ts
- packages/extension-base/src/koni/api/nft/transfer.ts
- packages/extension-koni-ui/src/Popup/Transaction/helper/nftParamsHandler.ts
- #2934 
- Support nfts pallet NFT on statemine
- Support nfts pallet NFT on statemine
- No
- No
> [Issue-2934] Support nfts pallet NFT on statemine

- packages/extension-base/src/services/earning-service/handlers/nomination-pool/index.ts
- packages/extension-base/src/types/yield/info/pallet.ts
> [Issue 2937] Update parsing erasStakers 

- packages/extension-base/src/services/earning-service/handlers/native-staking/relay-chain.ts
- #2655 
- Update logic for Aleph Node 13 release
- Update max nominations for native staking
- No
- No
> [Issue-2655] Update max nominations for AlephZero

- packages/extension-web-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/webapp/public/locales/zh/translation.json
> [Issue-2921] WebApp - Add warning message for cross chain transfer to an exchange (CEX)

- packages/extension-web-ui/src/Popup/Transaction/variants/Earn.tsx
> [Issue-2922] WebApp - Re-check min active stake for Relaychain

- packages/extension-base/src/services/history-service/index.ts
- packages/extension-base/src/services/history-service/subscan-history.ts
- #2955
- Fix error when parsing history
- Fix error when parsing history
- No
- No
> [Issue-2955] Extension - Do not show transaction history in case sender account null

- packages/extension-base/src/koni/api/nft/config.ts
- packages/extension-web-ui/src/Popup/Transaction/helper/nftParamsHandler.ts
> [Issue - 2954]WebApp - Support NFTs on Asset Hub

- packages/extension-koni-ui/src/Popup/Home/index.tsx
- packages/extension-koni-ui/src/contexts/WalletModalContext.tsx
> [Issue-2948] Extension - Hide popup Introducing Earning feature

- packages/extension-web-ui/src/Popup/Account/AccountExport.tsx
- packages/extension-web-ui/src/Popup/Account/RestoreJson.tsx
- packages/extension-web-ui/src/Popup/Keyring/ApplyMasterPassword/index.tsx
- packages/extension-web-ui/src/Popup/Keyring/ChangePassword.tsx
- packages/extension-web-ui/src/Popup/Keyring/CreatePassword.tsx
> [Issue-2973] WebApp - Add show/hide password for case input password

- packages/extension-koni-ui/src/components/Modal/Swap/SwapTermsOfServiceModal.tsx
> [Issue-3007] Extension: User can't hit the "Confirm" button on the ToS screen of the Swap feature

- packages/extension-base/src/koni/background/handlers/Extension.ts
- #3027
- Fix cannot signing with Avail mainnet
- Fix cannot signing with Avail mainnet
- No
- No
> [Issue-3027] Fix cannot signing with Avail mainnet

- packages/extension-base/src/services/chain-service/utils/index.ts
- #3037
- Fix auto connect but not active chains have updated provider
- Fix auto connect but not active chains have updated provider
- No
- No
> [Issue-3037] Network's status show incorrect

- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
> Re-handle free response for PSP22 get balance

- packages/extension-base/src/koni/api/dotsama/transfer.ts
- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
- packages/extension-base/src/services/chain-service/handler/EvmChainHandler.ts
- packages/extension-base/src/services/chain-service/handler/SubstrateChainHandler.ts
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-base/src/services/chain-service/utils/index.ts
- packages/extension-base/src/utils/gear/grc20.ts
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
- packages/extension-koni-ui/src/Popup/Settings/Tokens/FungibleTokenImport.tsx
- packages/extension-koni-ui/src/hooks/screen/nft/index.ts
- packages/extension-koni-ui/src/hooks/screen/nft/useGetFungibleContractSupportedChains.ts
- packages/extension-koni-ui/src/hooks/screen/nft/useGetNftContractSupportedChains.ts
> Support import custom GRC20

- packages/extension-base/src/koni/background/handlers/State.ts
- packages/extension-base/src/services/price-service/index.ts
- packages/extension-base/src/stores/CurrentCurrencyStore.ts
- packages/extension-base/src/stores/index.ts
- Handle the case of not resetting the wallet to the default state when click Erase all
- Auto reset currency in case upgrade version
> [Issue 3035] [fix] Extension - Handling errors related to currency setting state.

- packages/extension-base/src/services/chain-service/index.ts
> [Issue 3101] fix: bug missing custom tokens on applying patch

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/koni/api/nft/ordinal_nft/index.ts
- packages/extension-base/src/services/chain-service/index.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- #3115
- Fix cannot fetch Avail inscriptions
- Fix cannot fetch Avail inscriptions
- No
- No
> [Issue-3115] [Inscriptions] Fix error when fetching with Avail network

- packages/extension-base/src/services/transaction-service/index.ts
- #3121 
- Fix HTTP provider error when subscribe tx status
- Fix HTTP provider error when subscribe tx status
- No
- No
> [Issue-3115] [Extension] Update subscription for `evmWatchTransactionRequest` request

- packages/extension-base/src/core/substrate/nominationpools-pallet.ts
- packages/extension-base/src/core/substrate/system-pallet.ts
- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
> [Issue 3166] fix: balance calculation for system pallet v1

- packages/extension-web-ui/src/Popup/Home/History/index.tsx
> [Issue-3151] WebApp - Show duplicate transaction history when transfer local token

- packages/extension-base/src/koni/background/handlers/Mobile.ts
- packages/extension-base/src/storage/index.ts
> [Issue-3194] Fix bug can not backup data in Mobile App

- packages/extension-koni-ui/src/Popup/Root.tsx
- packages/extension-koni/src/background.ts
> [Issue-3098] Extension - Hide the popup Remind backup seed phrase

- packages/extension-koni-ui/src/components/StaticContent/Banner.tsx
- packages/extension-koni-ui/src/components/StaticContent/ContentGenerator.tsx
- packages/extension-koni-ui/src/hooks/static-content/useGetAppInstructionData.ts
> [Issue-2806] fix bug cannot see Instruction url and onclick hyperlink on popup

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/core/substrate/xcm-parser.ts
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-web-ui/package.json
- packages/extension-web-ui/src/Popup/Transaction/variants/SendFund.tsx
- yarn.lock
> Update warning for unstable XCM transfers 

- packages/extension-koni-ui/src/contexts/AppOnlineContentProvider.tsx
> [Issue-3218] Extension - Error can't read properties of undefined (reading 'filter')

- packages/extension-koni-ui/src/hooks/transaction/useHandleSubmitMultiTransaction.ts
> [Issue 1984] Fix bug handling warning on send fund

- package.json
- packages/extension-koni-ui/src/Popup/Home/Nfts/component/NftGalleryWrapper.tsx
- yarn.lock
> [Issue-3228] Remove model-viewer support

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/constants/ledger.ts
- packages/extension-koni-ui/src/hooks/account/usePreCheckAction.ts
- packages/extension-web-ui/src/constants/ledger.ts
- packages/extension-web-ui/src/hooks/account/usePreCheckAction.ts
- #3254
- Update hook `usePreCheckAction`
- Update hook `usePreCheckAction`
- No
- No
> Show incorrect screen when perform earning actions with Ledger's EVM account

- packages/extension-base/src/utils/metadata.ts
- #3259
- Fallback for `signedExtension` undefined
- Fallback for `signedExtension` undefined
- No
- No
> [Issue-3259] Extension - Cannot read properties of undefined (reading 'includes')

- packages/extension-koni-ui/src/Popup/Confirmations/parts/Sign/Substrate.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/SignConfirmation.tsx
- packages/extension-koni-ui/src/Popup/Confirmations/variants/Transaction/index.tsx
- packages/extension-koni-ui/src/hooks/transaction/confirmation/useMetadata.ts
> [Issue-3260] Extension - Update UI for the Signature request screen from dApp

- packages/extension-koni-ui/src/hooks/screen/home/useReceiveQR.ts
> [Issue-3283] Fix issue related to getting accounts when opening "receive" modal

- packages/extension-koni-ui/src/stores/utils/index.ts
> [Issue-3289] Extension - Bug Cannot read properties of undefined (reading 'filter') related to Mission pool

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- https://github.com/Koniverse/SubWallet-ChainList/issues/259
- Update stable version for chain-list
- Update stable version for chain-list
- No
- No
> [Chainlist] [Issue-259] Hotfix update chain-list stable version

- packages/extension-base/src/core/substrate/nominationpools-pallet.ts
> [Issue 3312] fix update balance calculation for relaychain

- packages/extension-base/src/services/earning-service/service.ts
- packages/extension-web-ui/src/Popup/Home/Earning/EarningEntry/EarningPositions/EarningPositionsBalance.tsx
- #3322
- Fix missing data with earning reward info
- Fix missing data with earning reward info
- No
- No
> [Issue-3322] Staking rewards not being updated for injected accounts on webapp

- packages/extension-base/src/services/earning-service/service.ts
- #3326
- Fix missing data with earning reward info
- Fix missing data with earning reward info
- No
- No
> [Issue-3326] Fix missing data with earning reward info

- packages/extension-web-ui/src/components/Field/Earning/EarningPoolSelector.tsx
- packages/extension-web-ui/src/components/StakingItem/StakingPoolItem.tsx
- packages/extension-web-ui/src/constants/earning/statusUi.ts
> [Issue-3217] WebApp - Show nomination pool with block status

- packages/extension-base/src/constants/staking.ts
- packages/extension-base/src/koni/api/staking/bonding/utils.ts
- packages/extension-base/src/services/earning-service/handlers/native-staking/relay-chain.ts
- packages/extension-base/src/services/earning-service/service.ts
- packages/extension-koni-ui/src/components/Field/Earning/EarningValidatorSelector.tsx
- packages/extension-koni-ui/src/utils/common/common.ts
- packages/extension-koni-ui/src/utils/earning.ts
- #3365
- Set default pool and default validator for Avail
- Set default pool and default validator for Avail
- No
- No
> [Issue-3365] Extension - Set default pool and default validator for Avail

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- Update chain info for `avail_mainnet`
- Update stable version for chain-list
- Update stable version for chain-list
- No
- No
> [Avail] Update stable version for chain-list

- packages/extension-koni-ui/src/Popup/Confirmations/parts/Sign/Substrate.tsx
- packages/extension-koni-ui/src/constants/ledger.ts
- #2982
- Integrate with Avail Ledger App
- Integrate with Avail Ledger App
- No
- No
> [Issue-2982] Integrate Avail Ledger app

- packages/extension-web-ui/src/Popup/Confirmations/parts/Sign/Substrate.tsx
- packages/extension-web-ui/src/constants/ledger.ts
> [Issue-3407] WebApp - Support Avail Ledger app

- packages/extension-web-ui/src/Popup/Home/Nfts/NftCollectionDetail.tsx
- packages/extension-web-ui/src/Popup/Home/Nfts/NftCollections.tsx
- packages/extension-web-ui/src/Popup/Home/Nfts/NftEntry.tsx
- packages/extension-web-ui/src/Popup/Home/Nfts/NftItemDetail.tsx
- packages/extension-web-ui/src/Popup/Home/Nfts/utils.ts
- packages/extension-web-ui/src/Popup/Home/PortfolioPage/index.tsx
- packages/extension-web-ui/src/Popup/router.tsx
- Refactor UI code for NFT feature
> [Issue-1902] Refactor nft UI source

- packages/extension-base/src/services/earning-service/handlers/liquid-staking/bifrost.ts
> [Issue 3413] WebApp - Do not show earning position for Bifrost liquid staking

- packages/extension-web-ui/src/Popup/Home/Statistics/index.tsx
> [Issue 2047] Recheck logic calculate the Staking value on the Statistics

- packages/extension-koni-ui/src/contexts/ThemeContext.tsx
> [Issue-3441] Fix issue related to input overflow width

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-base/src/services/keyring-service/context/handlers/Derive.ts
- packages/extension-base/src/services/keyring-service/context/handlers/Json.ts
- packages/extension-base/src/services/keyring-service/context/handlers/Ledger.ts
- packages/extension-base/src/services/keyring-service/context/handlers/Mnemonic.ts
- packages/extension-base/src/services/keyring-service/context/handlers/Secret.ts
- packages/extension-base/src/services/keyring-service/context/state.ts
- packages/extension-base/src/types/account/info/keyring.ts
- packages/extension-base/src/types/account/info/proxy.ts
- packages/extension-base/src/utils/account/transform.ts
- packages/extension-koni-ui/src/Popup/Account/ImportPrivateKey.tsx
- packages/extension-koni-ui/src/Popup/Home/index.tsx
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/components/Field/AddressInput.tsx
- packages/extension-koni-ui/src/components/Field/AddressInputNew.tsx
- packages/extension-koni-ui/src/components/Modal/AddressBook/AddressBookModal.tsx
- packages/extension-koni-ui/src/hooks/account/useGetAccountNetworkAddresses.tsx
- packages/extension-koni-ui/src/hooks/earning/useGroupYieldPosition.ts
- packages/extension-koni-ui/src/hooks/earning/useYieldPoolInfoByGroup.ts
- packages/extension-koni-ui/src/hooks/earning/useYieldPositionDetail.ts
- packages/extension-koni-ui/src/hooks/earning/useYieldRewardTotal.ts
- packages/extension-koni-ui/src/hooks/screen/home/index.ts
- packages/extension-koni-ui/src/hooks/screen/home/useGetChainSlugsByAccount.ts
- packages/extension-koni-ui/src/hooks/screen/home/useGetChainSlugsByAccountType.ts
- packages/extension-koni-ui/src/hooks/screen/home/useGetTokensBySettings.ts
- packages/extension-koni-ui/src/hooks/screen/home/useReceiveModalHelper.tsx
- packages/extension-koni-ui/src/utils/account/account.ts
- packages/extension-koni-ui/src/utils/chain/chain.ts
- packages/extension-koni-ui/src/utils/common/common.ts
- packages/extension-koni-ui/src/utils/index.ts
- #3462
- Filter chains, tokens and features for account types
- Filter chains, tokens and features for account types
- No
- No
> [Issue-3462] Unified account - Filter chains, tokens and features for account types

- packages/extension-base/src/services/mkt-campaign-service/index.ts
- packages/extension-base/src/services/mkt-campaign-service/types.ts
> [Issue-3468] Improve condition for Marketing campaign

- packages/extension-koni-ui/src/Popup/Account/ConnectLedger.tsx
- packages/extension-koni-ui/src/components/Field/ChainSelector.tsx
> [Issue-3452] Extension - Re-check UI on Transfer screen ( version 1.1.24)

- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailList.tsx
> [Issue-3550] Unified account - Bug related to the Buy token feature

- packages/extension-base/src/services/keyring-service/context/handlers/Json.ts
- packages/extension-koni-ui/src/Popup/Home/index.tsx
- packages/extension-koni-ui/src/components/Modal/RemindUpgradeUnifiedAccount.tsx
- packages/extension-koni-ui/src/components/Modal/index.tsx
- packages/extension-koni-ui/src/constants/common.ts
- packages/extension-koni-ui/src/constants/localStorage.ts
- packages/extension-koni-ui/src/constants/modal.ts
> [Issue-3505] Update the reminder modal when a new version is available.

- packages/extension-base/src/core/logic-validation/recipientAddress.ts
- packages/extension-base/src/core/utils.ts
- #3528
- Fix missing validate with legacy ledger account
- Fix missing validate with legacy ledger account
- No
- No
> [Issue-3528] Unified account - Fix bug validating recipient address

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- #3449
- #3528
- Fix some transfer error
- Fix some transfer error
- No
- No
> [Issue-3449] Support transfer on TON

- packages/extension-koni-ui/src/Popup/Transaction/variants/Swap.tsx
- packages/extension-koni-ui/src/components/Field/AccountAddressSelector.tsx
> [Issue-3570] Unified account - Fix some UI bugs

- packages/extension-base/src/core/utils.ts
> [Issue-3604] Unified account - Update content

- packages/extension-base/src/services/keyring-service/context/handlers/Modify.ts
- packages/extension-base/src/types/account/action/edit.ts
- packages/extension-koni-ui/src/Popup/Home/Tokens/DetailList.tsx
- packages/extension-koni-ui/src/components/Modal/Global/AddressQrModal.tsx
- packages/extension-koni-ui/src/components/Modal/TonWalletContractSelectorModal/index.tsx
> [Issue-3512] [Unified-account] Add feature to switch WalletContract version for ton (v4)

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
> [Issue-3608] [Unified-account] Improve validation check when clicking the Transfer button on Send token screen

- packages/extension-base/src/utils/account/derive.ts
- packages/extension-koni-ui/src/components/Modal/Global/AddressQrModal.tsx
- packages/extension-koni-ui/src/components/Modal/TonWalletContractSelectorModal/index.tsx
> [Issue-3512] [Unified-account] Add feature to switch WalletContract version for ton

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/components/Field/AccountAddressSelector.tsx
> [Issue-3649] Unified account - Improve UX on Send fund screen

- packages/extension-base/src/koni/background/handlers/Extension.ts
- packages/extension-koni-ui/src/Popup/Settings/AddressBook/index.tsx
- packages/extension-koni-ui/src/components/Modal/AddressBook/AddContactModal.tsx
> [Issue-3610] [Unified-account] Support save contact for TON address

- packages/extension-koni-ui/src/components/Field/AccountAddressSelector.tsx
> [Issue-3649] Update color placeholder for accountSelector

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/components/Field/AddressInputNew.tsx
> [Issue-3583] Unified account - Some UI bugs for Send TON

- packages/extension-koni-ui/src/Popup/Account/RestoreJson/index.tsx
- packages/extension-koni-ui/src/components/AccountProxy/AccountProxyBriefInfo.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/AccountSelectorModal.tsx
- packages/extension-koni-ui/src/components/Modal/Account/AccountNameModal.tsx
- packages/extension-koni-ui/src/components/Search/index.tsx
> [Issue-3686] Unified account - Improve some UI phrase 1

- packages/extension-base/src/services/keyring-service/context/handlers/Mnemonic.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/hooks/account/useHandleTonAccountWarning.tsx
> [Issue-3642] Unified account - Update content for some features

- packages/extension-base/src/services/balance-service/helpers/subscribe/index.ts
- packages/extension-base/src/services/chain-service/handler/SubstrateApi.ts
- #3711
- Hotfix handle api status
- Hotfix handle api status
- No
- No
> [Issue-3711] Hotfix handle api status

- packages/extension-web-ui/src/contexts/ThemeContext.tsx
> [Issue-3488] WebApp - UI bug in case import by seed phrase

- packages/extension-koni-ui/src/Popup/BuyTokens.tsx
- packages/extension-koni-ui/src/Popup/Settings/MissionPool/index.tsx
> [Issue-3733] Unified account - UI bug on the Mission pool screen and Buy token

- packages/extension-base/src/services/keyring-service/context/state.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-base/src/utils/account/transform.ts
- packages/extension-koni-ui/src/Popup/Account/AccountDetail/DerivedAccountList.tsx
- packages/extension-koni-ui/src/Popup/Account/AccountDetail/index.tsx
- packages/extension-koni-ui/src/types/navigation.ts
> [Issue-3696] Unified account - Show derivation information for derived account

- packages/extension-koni-ui/src/Popup/Account/ImportSeedPhrase.tsx
> [Issue-3696] Unified account - Show derivation information for derived account (update content)

- packages/extension-koni-ui/src/Popup/Account/AccountDetail/index.tsx
> [Issue-3696] Update UI for derivation

- packages/extension-base/src/services/keyring-service/context/handlers/Modify.ts
- packages/extension-base/src/services/keyring-service/context/state.ts
- packages/extension-base/src/services/keyring-service/index.ts
- packages/extension-base/src/utils/account/derive/info/solo.ts
- packages/extension-base/src/utils/account/derive/info/unified.ts
- packages/extension-base/src/utils/account/transform.ts
- packages/extension-koni-ui/src/Popup/Account/AccountDetail/index.tsx
- packages/extension-koni-ui/src/Popup/Account/AccountExport.tsx
- #3751
- Fix some issues related derived account
- Fix some issues related derived account
- No
- No
> [Issue-3751] Extension - Support export for Derived account

- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/AccountSelectorModal.tsx
- packages/extension-koni-ui/src/components/Modal/Selector/AccountSelector.tsx
- packages/extension-koni-ui/src/hooks/modal/useSelectAccount.ts
> [Issue-3755] Improve UI related to Account selector screen

- packages/extension-koni-ui/src/components/Modal/GlobalSearchTokenModal.tsx
- packages/extension-koni-ui/src/components/Modal/ReceiveModalNew/parts/TokenSelector.tsx
- packages/extension-koni-ui/src/hooks/screen/home/useCoreReceiveModalHelper.tsx
> [Issue-3756] Improve UI related to Select token screen

- packages/extension-base/src/services/chain-service/utils/index.ts
- packages/extension-koni-ui/src/Popup/Settings/Chains/ChainDetail.tsx
> [Issue 3747] Extension - Update Network details screen for TON

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- #3794
- Inactive `tinkernet` chain
- Inactive `tinkernet` chain
- No
- No
> [Issue-3794] Update chainlist

- packages/extension-koni-ui/src/components/Field/Earning/EarningPoolSelector.tsx
- #3001
- Fix reset pool target
- Fix reset pool target
- No
- No
> [Issue-3001] Extension - Error auto reset data on Pool field

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/core/substrate/xcm-parser.ts
- packages/extension-base/src/services/balance-service/helpers/subscribe/substrate/index.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- #3852
- Fix some error with foreign asset on asset hub
- Fix some error with foreign asset on asset hub
- No
- No
> [Issue-3852] Extension - Re-check transaction on Polkadot Asset Hub

- packages/extension-koni-ui/src/Popup/Home/index.tsx
- packages/extension-koni-ui/src/components/Layout/base/Home.tsx
- packages/extension-koni-ui/src/components/Layout/parts/SelectAccount/index.tsx
This PR resolves 'Round 1 : Enable search token feature.' of the issue
Related issue: #3958
> [Issue-3958] Extension - Improve search token (round 1)

- package.json
- packages/extension-base/package.json
- packages/extension-koni-ui/package.json
- packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
- packages/extension-koni-ui/src/Popup/Settings/Tokens/FungibleTokenImport.tsx
- packages/extension-koni-ui/src/utils/account/reformatContractAddress.ts
- packages/extension-web-ui/package.json
- yarn.lock
> [Issue-3974] Fix: cannot import token & NFT on Rootstock

- packages/extension-base/src/services/earning-service/constants/chains.ts
- https://github.com/Koniverse/SubWallet-ChainList/issues/360
- Support staking nomination pool
- Support staking nomination pool
- No
- No
> [Cere Network] Add staking support for CERE

- packages/extension-base/src/services/swap-service/handler/asset-hub/handler.ts
- packages/extension-base/src/services/swap-service/handler/base-handler.ts
- packages/extension-base/src/services/swap-service/handler/chainflip-handler.ts
- packages/extension-base/src/services/swap-service/handler/hydradx-handler.ts
- packages/extension-base/src/services/swap-service/handler/simpleswap-handler.ts
- #3590
- Fix cannot get XCM step when swap
- Fix cannot get XCM step when swap
- No
- No
> [Issue-3590] Support paying fee with non-native tokens on Asset Hub

- packages/extension-base/src/core/logic-validation/request.ts
- #4050
- Fix error when estimate fee with request from dApp
- Fix error when estimate fee with request from dApp
- No
- No
> [Issue-4050] Extension - Unable to estimate fee when signing for dApp

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/utils/patch.ts
- packages/extension-base/src/types/swap/index.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- yarn.lock
- #3901
- Update stable version for chain-list
- Update stable version for chain-list
- No
- No
> [Issue-3901] Update stable version for chain-list

- packages/extension-base/src/services/migration-service/index.ts
- packages/extension-base/src/services/migration-service/scripts/index.ts
- packages/extension-base/src/services/storage-service/DatabaseService.ts
- packages/extension-base/src/services/storage-service/db-stores/Migration.ts
- #3741
- Remove some migration script
- Remove some migration script
- No
- No
> [Issue-3741] Extension - Reset Auto-lock, Advanced phishing detection, Camera in case upgrade version

- packages/extension-base/src/services/price-service/coingecko.ts
> [Issue-4081] Show value of derivative token relative to the origin tokens

- .env.example
- .github/workflows/push-koni-dev.yml
- .github/workflows/push-master.yml
- .github/workflows/push-web-runner.yml
- .github/workflows/push-webapp.yml
- packages/extension-koni-ui/src/constants/buy/meld.ts
- packages/extension-koni-ui/src/utils/buy/meld.ts
- packages/extension-koni/webpack.shared.cjs
> [Issue-4198] refactor: Update logic for Meld wizard url

- packages/extension-base/src/services/chain-service/index.ts
> [Issue-4200] Hide RUNE and BRC-20 tokens

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/services/chain-service/utils/patch.ts
- packages/extension-koni-ui/package.json
- packages/extension-web-ui/package.json
- packages/subwallet-api-sdk/package.json
- yarn.lock
- #4410
- Update stable version for chain-list
- Update stable version for chain-list
- No
- No
> [Issue-4410] Extension - Update chainlist stable v0.2.107

- packages/extension-base/src/core/logic-validation/recipientAddress.ts
- packages/extension-koni-ui/src/components/Field/AddressInputNew.tsx
> [Issue-4486] fix: Temporarily hardcode to disable "Advanced address conversion" to prevent errors

- packages/extension-koni-ui/src/Popup/TransactionSubmission.tsx
> [Issue-4512] refactor: Update swap submission content

- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
- packages/extension-koni-ui/src/components/Field/TransactionFee/FeeEditor/index.tsx
This PR resolves two issues:
1. #4559 
2. #4585
> [Issue-4559] Extension - Update logic for networks/rpc that don't support custom fee on EVM system

- packages/extension-base/src/types/balance/transfer.ts
- packages/extension-base/src/utils/fee/transfer.ts
- packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
> [ISSUE-4706] Extension - Don't show toast message validate in case input amount < 1 when transfer Cardano
